In [43]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,Normalizer,MaxAbsScaler,MinMaxScaler,RobustScaler
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
import matplotlib.pyplot as pl
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv('wdbc.data',header=None)

In [3]:
df.head(10)

0  1      2      3       4       5        6        7        8   \
0    842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
1    842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
2  84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
3  84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4  84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
5    843786  M  12.45  15.70   82.57   477.1  0.12780  0.17000  0.15780   
6    844359  M  18.25  19.98  119.60  1040.0  0.09463  0.10900  0.11270   
7  84458202  M  13.71  20.83   90.20   577.9  0.11890  0.16450  0.09366   
8    844981  M  13.00  21.82   87.50   519.8  0.12730  0.19320  0.18590   
9  84501001  M  12.46  24.04   83.97   475.9  0.11860  0.23960  0.22730   

        9    ...        22     23      24      25      26      27      28  \
0  0.14710   ...     25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119   
1  0.07017   ...     24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416   
2  0.12790   ...     23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504   
3  0.10520   ...     14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869   
4  0.10430   ...     22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000   
5  0.08089   ...     15.47  23.75  103.40   741.6  0.1791  0.5249  0.5355   
6  0.07400   ...     22.88  27.66  153.20  1606.0  0.1442  0.2576  0.3784   
7  0.05985   ...     17.06  28.14  110.60   897.0  0.1654  0.3682  0.2678   
8  0.09353   ...     15.49  30.73  106.20   739.3  0.1703  0.5401  0.5390   
9  0.08543   ...     15.09  40.68   97.65   711.4  0.1853  1.0580  1.1050   

       29      30       31  
0  0.2654  0.4601  0.11890  
1  0.1860  0.2750  0.08902  
2  0.2430  0.3613  0.08758  
3  0.2575  0.6638  0.17300  
4  0.1625  0.2364  0.07678  
5  0.1741  0.3985  0.12440  
6  0.1932  0.3063  0.08368  
7  0.1556  0.3196  0.11510  
8  0.2060  0.4378  0.10720  
9  0.2210  0.4366  0.20750  

[10 rows x 32 columns]

In [4]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
dtype: int64

In [5]:
df.describe()

0           2           3           4            5   \
count  5.690000e+02  569.000000  569.000000  569.000000   569.000000   
mean   3.037183e+07   14.127292   19.289649   91.969033   654.889104   
std    1.250206e+08    3.524049    4.301036   24.298981   351.914129   
min    8.670000e+03    6.981000    9.710000   43.790000   143.500000   
25%    8.692180e+05   11.700000   16.170000   75.170000   420.300000   
50%    9.060240e+05   13.370000   18.840000   86.240000   551.100000   
75%    8.813129e+06   15.780000   21.800000  104.100000   782.700000   
max    9.113205e+08   28.110000   39.280000  188.500000  2501.000000   

               6           7           8           9           10     ...      \
count  569.000000  569.000000  569.000000  569.000000  569.000000     ...       
mean     0.096360    0.104341    0.088799    0.048919    0.181162     ...       
std      0.014064    0.052813    0.079720    0.038803    0.027414     ...       
min      0.052630    0.019380    0.000000    0.000000    0.106000     ...       
25%      0.086370    0.064920    0.029560    0.020310    0.161900     ...       
50%      0.095870    0.092630    0.061540    0.033500    0.179200     ...       
75%      0.105300    0.130400    0.130700    0.074000    0.195700     ...       
max      0.163400    0.345400    0.426800    0.201200    0.304000     ...       

               22          23          24           25          26  \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    16.269190   25.677223  107.261213   880.583128    0.132369   
std      4.833242    6.146258   33.602542   569.356993    0.022832   
min      7.930000   12.020000   50.410000   185.200000    0.071170   
25%     13.010000   21.080000   84.110000   515.300000    0.116600   
50%     14.970000   25.410000   97.660000   686.500000    0.131300   
75%     18.790000   29.720000  125.400000  1084.000000    0.146000   
max     36.040000   49.540000  251.200000  4254.000000    0.222600   

               27          28          29          30          31  
count  569.000000  569.000000  569.000000  569.000000  569.000000  
mean     0.254265    0.272188    0.114606    0.290076    0.083946  
std      0.157336    0.208624    0.065732    0.061867    0.018061  
min      0.027290    0.000000    0.000000    0.156500    0.055040  
25%      0.147200    0.114500    0.064930    0.250400    0.071460  
50%      0.211900    0.226700    0.099930    0.282200    0.080040  
75%      0.339100    0.382900    0.161400    0.317900    0.092080  
max      1.058000    1.252000    0.291000    0.663800    0.207500  

[8 rows x 31 columns]

In [6]:
Y = pd.DataFrame(df[1])
X = pd.DataFrame(df.iloc[:,2:])

encoder_y = LabelEncoder() 
Y = pd.DataFrame( encaoder_y.fit_transform(Y))

print(Y.shape,X.shape)
print(Y.dtypes)
print ' '
print(X.dtypes)

((569, 1), (569, 30))
0    int64
dtype: object
 
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
24    float64
25    float64
26    float64
27    float64
28    float64
29    float64
30    float64
31    float64
dtype: object


C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42 )

In [8]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

((455, 30), (455, 1))
((114, 30), (114, 1))


In [9]:
x_train.describe()

2           3           4            5           6   \
count  455.000000  455.000000  455.000000   455.000000  455.000000   
mean    14.117635   19.185033   91.882242   654.377582    0.095744   
std      3.535815    4.266005   24.322027   354.943187    0.013923   
min      7.691000    9.710000   47.920000   170.400000    0.052630   
25%     11.705000   16.170000   75.100000   420.300000    0.085825   
50%     13.300000   18.680000   85.980000   551.700000    0.094620   
75%     15.740000   21.585000  103.750000   767.600000    0.104550   
max     28.110000   39.280000  188.500000  2501.000000    0.163400   

               7           8           9           10          11     ...      \
count  455.000000  455.000000  455.000000  455.000000  455.000000     ...       
mean     0.103619    0.088898    0.048280    0.181099    0.062757     ...       
std      0.052470    0.079468    0.038060    0.027487    0.007210     ...       
min      0.019380    0.000000    0.000000    0.116700    0.049960     ...       
25%      0.062890    0.029320    0.020340    0.161850    0.057645     ...       
50%      0.090970    0.061540    0.033410    0.179200    0.061480     ...       
75%      0.131300    0.132350    0.073895    0.195800    0.066100     ...       
max      0.311400    0.426800    0.201200    0.304000    0.097440     ...       

               22          23          24           25          26  \
count  455.000000  455.000000  455.000000   455.000000  455.000000   
mean    16.235103   25.535692  107.103121   876.987033    0.131532   
std      4.811267    6.065108   33.374664   567.672841    0.023083   
min      8.678000   12.020000   54.490000   223.600000    0.071170   
25%     13.055000   21.045000   84.255000   516.450000    0.114400   
50%     14.970000   25.220000   97.670000   686.600000    0.130900   
75%     18.410000   29.690000  124.650000  1031.500000    0.146050   
max     36.040000   49.540000  251.200000  4254.000000    0.218400   

               27          28          29          30          31  
count  455.000000  455.000000  455.000000  455.000000  455.000000  
mean     0.252742    0.274595    0.114182    0.290502    0.083868  
std      0.155014    0.209398    0.065326    0.063151    0.017848  
min      0.027290    0.000000    0.000000    0.156500    0.055040  
25%      0.144950    0.116550    0.063930    0.249500    0.071050  
50%      0.210100    0.226400    0.098610    0.282700    0.080060  
75%      0.341600    0.387200    0.161100    0.317750    0.092070  
max      0.937900    1.252000    0.291000    0.663800    0.173000  

[8 rows x 30 columns]

In [10]:
x_test.describe()

2           3           4            5           6   \
count  114.000000  114.000000  114.000000   114.000000  114.000000   
mean    14.165833   19.707193   92.315439   656.930702    0.098820   
std      3.491876    4.432655   24.310746   341.074645    0.014415   
min      6.981000   10.940000   43.790000   143.500000    0.068280   
25%     11.687500   16.217500   75.225000   418.625000    0.088967   
50%     13.465000   19.535000   87.380000   548.700000    0.099085   
75%     16.057500   22.675000  105.300000   806.800000    0.106950   
max     25.220000   31.120000  171.500000  1878.000000    0.137100   

               7           8           9           10          11     ...      \
count  114.000000  114.000000  114.000000  114.000000  114.000000     ...       
mean     0.107221    0.088405    0.051471    0.181414    0.062961     ...       
std      0.054297    0.081070    0.041715    0.027240    0.006457     ...       
min      0.035580    0.000000    0.000000    0.106000    0.052660     ...       
25%      0.069655    0.030052    0.019842    0.163175    0.058427     ...       
50%      0.097565    0.062960    0.033950    0.179400    0.061580     ...       
75%      0.127800    0.119300    0.072968    0.193925    0.066405     ...       
max      0.345400    0.375400    0.184500    0.290600    0.082430     ...       

               22          23          24           25          26  \
count  114.000000  114.000000  114.000000   114.000000  114.000000   
mean    16.405237   26.242105  107.892193   894.935965    0.135707   
std      4.939138    6.456743   34.640172   578.333677    0.021581   
min      7.930000   12.490000   50.410000   185.200000    0.087990   
25%     12.850000   21.260000   84.012500   505.750000    0.121975   
50%     14.945000   25.790000   97.155000   681.200000    0.135850   
75%     19.695000   30.042500  129.175000  1211.000000    0.145175   
max     32.490000   47.160000  214.000000  3432.000000    0.222600   

               27          28          29          30          31  
count  114.000000  114.000000  114.000000  114.000000  114.000000  
mean     0.260345    0.262585    0.116299    0.288373    0.084257  
std      0.166857    0.206139    0.067596    0.056683    0.018967  
min      0.054940    0.000000    0.000000    0.156600    0.059050  
25%      0.150850    0.102495    0.069250    0.251600    0.072400  
50%      0.215550    0.228450    0.101500    0.280850    0.079750  
75%      0.316275    0.369850    0.166950    0.318925    0.092120  
max      1.058000    1.105000    0.286700    0.544000    0.207500  

[8 rows x 30 columns]

In [11]:
y_train.columns = ['label']
corr = pd.concat([x_train, y_train ], axis=1).corr()
corr.style.background_gradient(cmap='coolwarm')

In [12]:
# coluna com pouca relacao com a label 11,13 e 16
# depois temos 20 e 21

In [13]:
standardscales = StandardScaler()
normalize = Normalizer()
maxabsscaler = MaxAbsScaler()
minmaxscaler = MinMaxScaler()
robustscaler = RobustScaler()

x_train_norma0 = pd.DataFrame(standardscales.fit_transform(x_train))
x_train_norma1 = pd.DataFrame(normalize.fit_transform(x_train))
x_train_norma2 = pd.DataFrame(maxabsscaler.fit_transform(x_train))
x_train_norma3 = pd.DataFrame(minmaxscaler.fit_transform(x_train))
x_train_norma4 = pd.DataFrame(robustscaler.fit_transform(x_train))

In [14]:
x_train_norma0.describe()

0             1             2             3             4   \
count  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02   
mean  -3.347749e-16 -4.599495e-17 -8.808583e-17  3.589314e-16 -2.000841e-16   
std    1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00   
min   -1.819583e+00 -2.223500e+00 -1.809497e+00 -1.365036e+00 -3.100011e+00   
25%   -6.830930e-01 -7.075360e-01 -6.907613e-01 -6.602049e-01 -7.132037e-01   
50%   -2.314983e-01 -1.185158e-01 -2.429378e-01 -2.895973e-01 -8.082013e-02   
75%    4.593426e-01  5.631988e-01  4.884799e-01  3.193386e-01  6.331729e-01   
max    3.961679e+00  4.715674e+00  3.976811e+00  5.208312e+00  4.864642e+00   

                 5             6             7             8             9   \
count  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02   
mean   1.927640e-16 -1.037022e-16  2.383929e-16  1.277366e-16  4.289609e-16   
std    1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00   
min   -1.607228e+00 -1.119899e+00 -1.269910e+00 -2.345430e+00 -1.776889e+00   
25%   -7.770872e-01 -7.505387e-01 -7.349048e-01 -7.010461e-01 -7.097920e-01   
50%   -2.413402e-01 -3.446456e-01 -3.911235e-01 -6.915087e-02 -1.772851e-01   
75%    5.281282e-01  5.473870e-01  6.737569e-01  5.354290e-01  4.642225e-01   
max    3.964311e+00  4.256736e+00  4.022271e+00  4.476124e+00  4.815921e+00   

           ...                 20            21            22            23  \
count      ...       4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02   
mean       ...      -5.319310e-17 -6.734540e-16 -2.513252e-17  1.917880e-16   
std        ...       1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00   
min        ...      -1.572438e+00 -2.230887e+00 -1.578174e+00 -1.152259e+00   
25%        ...      -6.616975e-01 -7.412292e-01 -6.853483e-01 -6.358132e-01   
50%        ...      -2.632354e-01 -5.210786e-02 -2.829543e-01 -3.357508e-01   
75%        ...       4.525400e-01  6.857059e-01  5.263332e-01  2.724862e-01   
max        ...       4.120889e+00  3.962127e+00  4.322305e+00  5.955420e+00   

                 24            25            26            27            28  \
count  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02   
mean  -2.098444e-17 -2.318048e-16 -6.636938e-17 -8.174170e-17  4.750779e-16   
std    1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00   
min   -2.617938e+00 -1.455995e+00 -1.312795e+00 -1.749805e+00 -2.124261e+00   
25%   -7.430298e-01 -6.961323e-01 -7.555873e-01 -7.700987e-01 -6.499846e-01   
50%   -2.741590e-02 -2.753858e-01 -2.304110e-01 -2.386392e-01 -1.236838e-01   
75%    6.296478e-01  5.738568e-01  5.383496e-01  7.189995e-01  4.319440e-01   
max    3.767506e+00  4.424833e+00  4.672828e+00  2.709674e+00  5.917679e+00   

                 29  
count  4.550000e+02  
mean   2.440051e-19  
std    1.001101e+00  
min   -1.616973e+00  
25%   -7.189616e-01  
50%   -2.135847e-01  
75%    4.600643e-01  
max    4.999482e+00  

[8 rows x 30 columns]

In [15]:
x_train_norma1.describe()

0           1           2           3           4           5   \
count  455.000000  455.000000  455.000000  455.000000  455.000000  455.000000   
mean     0.014863    0.021948    0.096138    0.605734    0.000112    0.000110   
std      0.003995    0.010875    0.024869    0.047093    0.000057    0.000069   
min      0.005512    0.004568    0.037570    0.376233    0.000022    0.000024   
25%      0.011968    0.013986    0.078214    0.584678    0.000073    0.000067   
50%      0.015061    0.020352    0.097171    0.615304    0.000103    0.000092   
75%      0.017281    0.027058    0.110912    0.639583    0.000139    0.000132   
max      0.026184    0.086609    0.164570    0.697401    0.000407    0.000557   

               6           7           8           9      ...              20  \
count  455.000000  455.000000  455.000000  455.000000     ...      455.000000   
mean     0.000081    0.000042    0.000212    0.000076     ...        0.016753   
std      0.000079    0.000023    0.000110    0.000043     ...        0.003987   
min      0.000000    0.000000    0.000041    0.000011     ...        0.007245   
25%      0.000040    0.000027    0.000138    0.000046     ...        0.014108   
50%      0.000063    0.000038    0.000194    0.000069     ...        0.016703   
75%      0.000103    0.000053    0.000262    0.000094     ...        0.019211   
max      0.000826    0.000161    0.000693    0.000264     ...        0.029544   

               21          22          23          24          25          26  \
count  455.000000  455.000000  455.000000  455.000000  455.000000  455.000000   
mean     0.029071    0.109826    0.776771    0.000154    0.000263    0.000268   
std      0.014257    0.025120    0.037648    0.000082    0.000183    0.000251   
min      0.005154    0.050496    0.696047    0.000027    0.000042    0.000000   
25%      0.018085    0.093354    0.749435    0.000099    0.000146    0.000142   
50%      0.027027    0.109760    0.768914    0.000140    0.000217    0.000213   
75%      0.036626    0.125512    0.798082    0.000188    0.000323    0.000326   
max      0.108567    0.185508    0.921243    0.000543    0.001474    0.002974   

               27          28          29  
count  455.000000  455.000000  455.000000  
mean     0.000109    0.000336    0.000099  
std      0.000054    0.000168    0.000056  
min      0.000000    0.000046    0.000015  
25%      0.000077    0.000226    0.000061  
50%      0.000101    0.000311    0.000089  
75%      0.000133    0.000415    0.000122  
max      0.000416    0.001004    0.000445  

[8 rows x 30 columns]

In [16]:
x_train_norma2.describe().round(3)

0        1        2        3        4        5        6        7   \
count  455.000  455.000  455.000  455.000  455.000  455.000  455.000  455.000   
mean     0.502    0.488    0.487    0.262    0.586    0.333    0.208    0.240   
std      0.126    0.109    0.129    0.142    0.085    0.168    0.186    0.189   
min      0.274    0.247    0.254    0.068    0.322    0.062    0.000    0.000   
25%      0.416    0.412    0.398    0.168    0.525    0.202    0.069    0.101   
50%      0.473    0.476    0.456    0.221    0.579    0.292    0.144    0.166   
75%      0.560    0.550    0.550    0.307    0.640    0.422    0.310    0.367   
max      1.000    1.000    1.000    1.000    1.000    1.000    1.000    1.000   

            8        9    ...          20       21       22       23       24  \
count  455.000  455.000   ...     455.000  455.000  455.000  455.000  455.000   
mean     0.596    0.644   ...       0.450    0.515    0.426    0.206    0.602   
std      0.090    0.074   ...       0.133    0.122    0.133    0.133    0.106   
min      0.384    0.513   ...       0.241    0.243    0.217    0.053    0.326   
25%      0.532    0.592   ...       0.362    0.425    0.335    0.121    0.524   
50%      0.589    0.631   ...       0.415    0.509    0.389    0.161    0.599   
75%      0.644    0.678   ...       0.511    0.599    0.496    0.242    0.669   
max      1.000    1.000   ...       1.000    1.000    1.000    1.000    1.000   

            25       26       27       28       29  
count  455.000  455.000  455.000  455.000  455.000  
mean     0.269    0.219    0.392    0.438    0.485  
std      0.165    0.167    0.224    0.095    0.103  
min      0.029    0.000    0.000    0.236    0.318  
25%      0.155    0.093    0.220    0.376    0.411  
50%      0.224    0.181    0.339    0.426    0.463  
75%      0.364    0.309    0.554    0.479    0.532  
max      1.000    1.000    1.000    1.000    1.000  

[8 rows x 30 columns]

In [17]:
x_train_norma3.describe().round(3)

0        1        2        3        4        5        6        7   \
count  455.000  455.000  455.000  455.000  455.000  455.000  455.000  455.000   
mean     0.315    0.320    0.313    0.208    0.389    0.288    0.208    0.240   
std      0.173    0.144    0.173    0.152    0.126    0.180    0.186    0.189   
min      0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000   
25%      0.197    0.218    0.193    0.107    0.300    0.149    0.069    0.101   
50%      0.275    0.303    0.271    0.164    0.379    0.245    0.144    0.166   
75%      0.394    0.402    0.397    0.256    0.469    0.383    0.310    0.367   
max      1.000    1.000    1.000    1.000    1.000    1.000    1.000    1.000   

            8        9    ...          20       21       22       23       24  \
count  455.000  455.000   ...     455.000  455.000  455.000  455.000  455.000   
mean     0.344    0.270   ...       0.276    0.360    0.267    0.162    0.410   
std      0.147    0.152   ...       0.176    0.162    0.170    0.141    0.157   
min      0.000    0.000   ...       0.000    0.000    0.000    0.000    0.000   
25%      0.241    0.162   ...       0.160    0.241    0.151    0.073    0.294   
50%      0.334    0.243   ...       0.230    0.352    0.220    0.115    0.406   
75%      0.422    0.340   ...       0.356    0.471    0.357    0.200    0.509   
max      1.000    1.000   ...       1.000    1.000    1.000    1.000    1.000   

            25       26       27       28       29  
count  455.000  455.000  455.000  455.000  455.000  
mean     0.248    0.219    0.392    0.264    0.244  
std      0.170    0.167    0.224    0.124    0.151  
min      0.000    0.000    0.000    0.000    0.000  
25%      0.129    0.093    0.220    0.183    0.136  
50%      0.201    0.181    0.339    0.249    0.212  
75%      0.345    0.309    0.554    0.318    0.314  
max      1.000    1.000    1.000    1.000    1.000  

[8 rows x 30 columns]

In [18]:
x_train_norma4.describe()

0           1           2           3           4           5   \
count  455.000000  455.000000  455.000000  455.000000  455.000000  455.000000   
mean     0.202636    0.093266    0.206012    0.295645    0.060028    0.184905   
std      0.876286    0.787812    0.848936    1.022007    0.743552    0.767000   
min     -1.390087   -1.656510   -1.328447   -1.097898   -2.242457   -1.046484   
25%     -0.395291   -0.463527   -0.379756   -0.378347   -0.469693   -0.410466   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.604709    0.536473    0.620244    0.621653    0.530307    0.589534   
max      3.670384    3.804247    3.578360    5.612727    3.673164    3.222190   

               6           7           8           9      ...              20  \
count  455.000000  455.000000  455.000000  455.000000     ...      455.000000   
mean     0.265536    0.277656    0.055926    0.151008     ...        0.236247   
std      0.771308    0.710675    0.809641    0.852716     ...        0.898463   
min     -0.597302   -0.623845   -1.840943   -1.362507     ...       -1.174977   
25%     -0.312724   -0.244048   -0.511046   -0.453578     ...       -0.357610   
50%      0.000000    0.000000    0.000000    0.000000     ...        0.000000   
75%      0.687276    0.755952    0.488954    0.546422     ...        0.642390   
max      3.545181    3.133041    3.675994    4.253105     ...        3.934641   

               21          22          23          24          25          26  \
count  455.000000  455.000000  455.000000  455.000000  455.000000  455.000000   
mean     0.036517    0.233522    0.369648    0.019973    0.216841    0.178070   
std      0.701574    0.826208    1.102170    0.729305    0.788275    0.773686   
min     -1.526894   -1.068944   -0.898942   -1.887204   -0.929621   -0.836505   
25%     -0.482938   -0.332096   -0.330356   -0.521327   -0.331299   -0.405875   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.517062    0.667904    0.669644    0.478673    0.668701    0.594125   
max      2.813187    3.800718    6.926318    2.764613    3.700992    3.789396   

               27          28          29  
count  455.000000  455.000000  455.000000  
mean     0.160258    0.114318    0.181153  
std      0.672287    0.925293    0.849091  
min     -1.014819   -1.849084   -1.190295  
25%     -0.356900   -0.486447   -0.428639  
50%      0.000000    0.000000    0.000000  
75%      0.643100    0.513553    0.571361  
max      1.979932    5.583883    4.421503  

[8 rows x 30 columns]

In [19]:
standardscales = StandardScaler()
normalize = Normalizer()
maxabsscaler = MaxAbsScaler()
minmaxscaler = MinMaxScaler()
robustscaler = RobustScaler()

x_test_norma0 = pd.DataFrame(standardscales.fit_transform(x_test))
x_test_norma1 = pd.DataFrame(normalize.fit_transform(x_test))
x_test_norma2 = pd.DataFrame(maxabsscaler.fit_transform(x_test))
x_test_norma3 = pd.DataFrame(minmaxscaler.fit_transform(x_test))
x_test_norma4 = pd.DataFrame(robustscaler.fit_transform(x_test))

In [20]:
x_test_norma0.describe()

0             1             2             3             4   \
count  1.140000e+02  1.140000e+02  1.140000e+02  1.140000e+02  1.140000e+02   
mean  -2.921640e-17  1.137492e-15 -2.785296e-16  3.661788e-16  3.423188e-16   
std    1.004415e+00  1.004415e+00  1.004415e+00  1.004415e+00  1.004415e+00   
min   -2.066670e+00 -1.986597e+00 -2.004862e+00 -1.511978e+00 -2.128007e+00   
25%   -7.128761e-01 -7.907451e-01 -7.061031e-01 -7.017755e-01 -6.865114e-01   
50%   -2.015901e-01 -3.901798e-02 -2.039110e-01 -3.187236e-01  1.847119e-02   
75%    5.441254e-01  6.724886e-01  5.364660e-01  4.413432e-01  5.665006e-01   
max    3.179658e+00  2.586079e+00  3.271564e+00  3.595871e+00  2.667338e+00   

                 5             6             7             8             9   \
count  1.140000e+02  1.140000e+02  1.140000e+02  1.140000e+02  1.140000e+02   
mean   9.276206e-17 -1.304999e-16  1.860111e-16  8.704051e-16  1.707211e-15   
std    1.004415e+00  1.004415e+00  1.004415e+00  1.004415e+00  1.004415e+00   
min   -1.325256e+00 -1.095284e+00 -1.239323e+00 -2.780749e+00 -1.602290e+00   
25%   -6.949201e-01 -7.229515e-01 -7.615503e-01 -6.725298e-01 -7.051387e-01   
50%   -1.786273e-01 -3.152469e-01 -4.218663e-01 -7.426372e-02 -2.147584e-01   
75%    3.806746e-01  3.827725e-01  5.176067e-01  4.613181e-01  5.357840e-01   
max    4.405946e+00  3.555701e+00  3.203114e+00  4.026025e+00  3.028518e+00   

           ...                 20            21            22            23  \
count      ...       1.140000e+02  1.140000e+02  1.140000e+02  1.140000e+02   
mean       ...       5.219996e-16  3.194326e-16  9.738798e-17 -1.947760e-16   
std        ...       1.004415e+00  1.004415e+00  1.004415e+00  1.004415e+00   
min        ...      -1.723510e+00 -2.139286e+00 -1.666735e+00 -1.232627e+00   
25%        ...      -7.229872e-01 -7.750194e-01 -6.924077e-01 -6.759147e-01   
50%        ...      -2.969514e-01 -7.032978e-02 -3.113321e-01 -3.712037e-01   
75%        ...       6.690009e-01  5.911918e-01  6.171093e-01  5.489209e-01   
max        ...       3.270971e+00  3.254001e+00  3.076667e+00  4.406220e+00   

                 24            25            26            27            28  \
count  1.140000e+02  1.140000e+02  1.140000e+02  1.140000e+02  1.140000e+02   
mean  -6.191441e-16 -1.743854e-17  1.446212e-16 -1.051790e-16  1.909413e-15   
std    1.004415e+00  1.004415e+00  1.004415e+00  1.004415e+00  1.004415e+00   
min   -2.220832e+00 -1.236454e+00 -1.279450e+00 -1.728078e+00 -2.334990e+00   
25%   -6.391145e-01 -6.591139e-01 -7.800418e-01 -6.990934e-01 -6.516074e-01   
50%    6.650554e-03 -2.696458e-01 -1.663244e-01 -2.198909e-01 -1.333028e-01   
75%    4.406512e-01  3.366783e-01  5.226489e-01  7.526301e-01  5.413792e-01   
max    4.044137e+00  4.801565e+00  4.104677e+00  2.531994e+00  4.529667e+00   

                 29  
count  1.140000e+02  
mean   1.849154e-15  
std    1.004415e+00  
min   -1.334843e+00  
25%   -6.278907e-01  
50%   -2.386700e-01  
75%    4.163858e-01  
max    6.526356e+00  

[8 rows x 30 columns]

In [21]:
x_test_norma1.describe()

0           1           2           3           4           5   \
count  114.000000  114.000000  114.000000  114.000000  114.000000  114.000000   
mean     0.014763    0.022259    0.095478    0.602489    0.000115    0.000109   
std      0.004091    0.011894    0.025187    0.047950    0.000063    0.000051   
min      0.005560    0.006070    0.036396    0.380592    0.000025    0.000031   
25%      0.011041    0.014614    0.072933    0.578555    0.000070    0.000074   
50%      0.015047    0.020313    0.096839    0.614782    0.000107    0.000100   
75%      0.017517    0.026716    0.113330    0.636825    0.000144    0.000134   
max      0.028470    0.080140    0.178585    0.669741    0.000477    0.000309   

               6           7           8           9      ...              20  \
count  114.000000  114.000000  114.000000  114.000000     ...      114.000000   
mean     0.000072    0.000042    0.000212    0.000075     ...        0.016710   
std      0.000046    0.000022    0.000116    0.000044     ...        0.004112   
min      0.000000    0.000000    0.000046    0.000015     ...        0.008714   
25%      0.000035    0.000026    0.000129    0.000042     ...        0.013487   
50%      0.000067    0.000041    0.000190    0.000069     ...        0.016871   
75%      0.000104    0.000057    0.000283    0.000095     ...        0.019266   
max      0.000262    0.000113    0.000787    0.000319     ...        0.032340   

               21          22          23          24          25          26  \
count  114.000000  114.000000  114.000000  114.000000  114.000000  114.000000   
mean     0.029524    0.108959    0.779349    0.000158    0.000255    0.000231   
std      0.015266    0.025257    0.038133    0.000086    0.000143    0.000162   
min      0.007307    0.057397    0.721752    0.000037    0.000071    0.000000   
25%      0.018762    0.087874    0.751594    0.000098    0.000154    0.000126   
50%      0.026801    0.109904    0.769257    0.000151    0.000240    0.000209   
75%      0.035814    0.125812    0.803429    0.000197    0.000320    0.000310   
max      0.097212    0.205583    0.920500    0.000646    0.001220    0.001274   

               27          28          29  
count  114.000000  114.000000  114.000000  
mean     0.000105    0.000333    0.000097  
std      0.000046    0.000178    0.000054  
min      0.000000    0.000074    0.000022  
25%      0.000082    0.000207    0.000060  
50%      0.000104    0.000299    0.000092  
75%      0.000124    0.000436    0.000118  
max      0.000255    0.001196    0.000383  

[8 rows x 30 columns]

In [22]:
x_test_norma2.describe()

0           1           2           3           4           5   \
count  114.000000  114.000000  114.000000  114.000000  114.000000  114.000000   
mean     0.561690    0.633265    0.538282    0.349803    0.720787    0.310427   
std      0.138457    0.142437    0.141754    0.181616    0.105141    0.157201   
min      0.276804    0.351542    0.255335    0.076411    0.498031    0.103011   
25%      0.463422    0.521128    0.438630    0.222910    0.648924    0.201665   
50%      0.533902    0.627731    0.509504    0.292173    0.722721    0.282470   
75%      0.636697    0.728631    0.613994    0.429606    0.780088    0.370006   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               6           7           8           9      ...              20  \
count  114.000000  114.000000  114.000000  114.000000     ...      114.000000   
mean     0.235495    0.278974    0.624274    0.763807     ...        0.504932   
std      0.215957    0.226096    0.093736    0.078334     ...        0.152020   
min      0.000000    0.000000    0.364763    0.638845     ...        0.244075   
25%      0.080055    0.107547    0.561511    0.708814     ...        0.395506   
50%      0.167714    0.184011    0.617343    0.747058     ...        0.459988   
75%      0.317794    0.395488    0.667326    0.805593     ...        0.606187   
max      1.000000    1.000000    1.000000    1.000000     ...        1.000000   

               21          22          23          24          25          26  \
count  114.000000  114.000000  114.000000  114.000000  114.000000  114.000000   
mean     0.556448    0.504169    0.260762    0.609646    0.246072    0.237634   
std      0.136911    0.161870    0.168512    0.096950    0.157710    0.186551   
min      0.264843    0.235561    0.053963    0.395283    0.051928    0.000000   
25%      0.450806    0.392582    0.147363    0.547956    0.142580    0.092756   
50%      0.546862    0.453995    0.198485    0.610288    0.203733    0.206742   
75%      0.637034    0.603621    0.352855    0.652179    0.298937    0.334706   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               27          28          29  
count  114.000000  114.000000  114.000000  
mean     0.405645    0.530097    0.406058  
std      0.235774    0.104197    0.091408  
min      0.000000    0.287868    0.284578  
25%      0.241542    0.462500    0.348916  
50%      0.354029    0.516268    0.384337  
75%      0.582316    0.586259    0.443952  
max      1.000000    1.000000    1.000000  

[8 rows x 30 columns]

In [23]:
x_test_norma3.describe()

0           1           2           3           4           5   \
count  114.000000  114.000000  114.000000  114.000000  114.000000  114.000000   
mean     0.393927    0.434450    0.379966    0.296011    0.443765    0.231235   
std      0.191451    0.219656    0.190359    0.196641    0.209456    0.175254   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.258046    0.261521    0.246144    0.158619    0.300603    0.109983   
50%      0.355502    0.425917    0.341320    0.233612    0.447617    0.200068   
75%      0.497642    0.581516    0.481638    0.382416    0.561901    0.297657   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               6           7           8           9      ...              20  \
count  114.000000  114.000000  114.000000  114.000000     ...      114.000000   
mean     0.235495    0.278974    0.408527    0.346007     ...        0.345083   
std      0.215957    0.226096    0.147561    0.216898     ...        0.201105   
min      0.000000    0.000000    0.000000    0.000000     ...        0.000000   
25%      0.080055    0.107547    0.309724    0.193735     ...        0.200326   
50%      0.167714    0.184011    0.397616    0.299631     ...        0.285627   
75%      0.317794    0.395488    0.476300    0.461706     ...        0.479031   
max      1.000000    1.000000    1.000000    1.000000     ...        1.000000   

               21          22          23          24          25          26  \
count  114.000000  114.000000  114.000000  114.000000  114.000000  114.000000   
mean     0.396657    0.351380    0.218596    0.354484    0.204778    0.237634   
std      0.186234    0.211750    0.178124    0.160322    0.166348    0.186551   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.252956    0.205407    0.098728    0.252470    0.095617    0.092756   
50%      0.383617    0.285745    0.152766    0.355546    0.160120    0.206742   
75%      0.506273    0.481478    0.315942    0.424820    0.260538    0.334706   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               27          28          29  
count  114.000000  114.000000  114.000000  
mean     0.405645    0.340147    0.169801  
std      0.235774    0.146317    0.127769  
min      0.000000    0.000000    0.000000  
25%      0.241542    0.245225    0.089929  
50%      0.354029    0.320728    0.139441  
75%      0.582316    0.419011    0.222769  
max      1.000000    1.000000    1.000000  

[8 rows x 30 columns]

In [24]:
x_test_norma4.describe()

0           1           2             3             4   \
count  1.140000e+02  114.000000  114.000000  1.140000e+02  1.140000e+02   
mean   1.603738e-01    0.026666    0.164104  2.788194e-01 -1.474143e-02   
std    7.990564e-01    0.686435    0.808337  8.786621e-01  8.016005e-01   
min   -1.483753e+00   -1.331010   -1.449377 -1.043859e+00 -1.713054e+00   
25%   -4.067506e-01   -0.513744   -0.404156 -3.350937e-01 -5.626303e-01   
50%    2.032879e-16    0.000000    0.000000 -1.465841e-16 -3.859760e-16   
75%    5.932494e-01    0.486256    0.595844  6.649063e-01  4.373697e-01   
max    2.689931e+00    1.794038    2.797007  3.424486e+00  2.114000e+00   

               5             6           7           8           9   \
count  114.000000  1.140000e+02  114.000000  114.000000  114.000000   
mean     0.166073  2.851045e-01    0.329800    0.065497    0.173063   
std      0.933823  9.083777e-01    0.785216    0.885846    0.809410   
min     -1.066042 -7.054539e-01   -0.639059   -2.386992   -1.118145   
25%     -0.480007 -3.687218e-01   -0.265553   -0.527642   -0.395174   
50%      0.000000  3.816392e-17    0.000000    0.000000    0.000000   
75%      0.519993  6.312782e-01    0.734447    0.472358    0.604826   
max      4.262361  3.500826e+00    2.833882    3.616260    2.613601   

          ...              20            21          22            23  \
count     ...      114.000000  1.140000e+02  114.000000  1.140000e+02   
mean      ...        0.213329  5.147797e-02    0.237746  3.030641e-01   
std       ...        0.721569  7.351828e-01    0.767012  8.200407e-01   
min       ...       -1.024836 -1.514375e+00   -1.035040 -7.032967e-01   
25%       ...       -0.306063 -5.157985e-01   -0.291005 -2.487770e-01   
50%       ...        0.000000  2.022037e-16    0.000000 -8.066464e-17   
75%       ...        0.693937  4.842015e-01    0.708995  7.512230e-01   
max       ...        2.563185  2.433248e+00    2.587213  3.900461e+00   

               24            25            26          27            28  \
count  114.000000  1.140000e+02  1.140000e+02  114.000000  1.140000e+02   
mean    -0.006159  2.707852e-01  1.276776e-01    0.151469  1.117387e-01   
std      0.930216  1.008659e+00  7.710311e-01    0.691878  8.419332e-01   
min     -2.062931 -9.708932e-01 -8.544819e-01   -1.038895 -1.845525e+00   
25%     -0.598060 -3.911138e-01 -4.711152e-01   -0.330092 -4.344597e-01   
50%      0.000000 -8.413409e-17  5.204170e-17    0.000000 -4.122137e-16   
75%      0.401940  6.088862e-01  5.288848e-01    0.669908  5.655403e-01   
max      3.739224  5.092640e+00  3.278600e+00    1.895599  3.908652e+00   

               29  
count  114.000000  
mean     0.228551  
std      0.961829  
min     -1.049696  
25%     -0.372718  
50%      0.000000  
75%      0.627282  
max      6.478195  

[8 rows x 30 columns]

In [54]:
# x_train_norma0 = standardscales

rf = RandomForestClassifier()
rf.fit(x_train_norma0, y_train)

pred = rf.predict(x_train_norma0)
print ('standardscales')
print('accuracy', accuracy_score(y_train,pred))
print('precision', precision_score(y_train,pred ))
print('recall', recall_score(y_train,pred))
print('f1', f1_score(y_train,pred))
confusion_matrix(y_train,pred)

standardscales
('accuracy', 0.9978021978021978)
('precision', 1.0)
('recall', 0.9940828402366864)
('f1', 0.9970326409495549)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([[286,   0],
       [  1, 168]], dtype=int64)

In [26]:
# x_train_norma1 = normalize

rf1 = RandomForestClassifier()
rf1.fit(x_train_norma1, y_train)

pred1 = rf1.predict(x_train_norma1)
print ('normalize')
print('accuracy', accuracy_score(y_train,pred1))
print('precision', precision_score(y_train,pred1 ))
print('recall', recall_score(y_train,pred1))
print('f1', f1_score(y_train,pred1))
confusion_matrix(y_train,pred1)

normalize
('accuracy', 1.0)
('precision', 1.0)
('recall', 1.0)
('f1', 1.0)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([[286,   0],
       [  0, 169]], dtype=int64)

In [27]:
# x_train_norma2 = maxabsscaler

rf2 = RandomForestClassifier()
rf2.fit(x_train_norma2, y_train)

pred2 = rf2.predict(x_train_norma2)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_train,pred2))
print('precision', precision_score(y_train,pred2 ))
print('recall', recall_score(y_train,pred2))
print('f1', f1_score(y_train,pred2))
confusion_matrix(y_train,pred2)

maxabsscaler
('accuracy', 1.0)
('precision', 1.0)
('recall', 1.0)
('f1', 1.0)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([[286,   0],
       [  0, 169]], dtype=int64)

In [28]:
# x_train_norma3 = minmaxscaler

rf3 = RandomForestClassifier()
rf3.fit(x_train_norma3, y_train)

pred3 = rf3.predict(x_train_norma3)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_train,pred3))
print('precision', precision_score(y_train,pred3 ))
print('recall', recall_score(y_train,pred3))
print('f1', f1_score(y_train,pred3))
confusion_matrix(y_train,pred3)

C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


minmaxscaler
('accuracy', 0.9978021978021978)
('precision', 1.0)
('recall', 0.9940828402366864)
('f1', 0.9970326409495549)


array([[286,   0],
       [  1, 168]], dtype=int64)

In [29]:
# x_train_norma4 = robustscaler

rf4 = RandomForestClassifier()
rf4.fit(x_train_norma4, y_train)

pred4 = rf4.predict(x_train_norma4)
print ('robustscaler')
print('accuracy', accuracy_score(y_train,pred4))
print('precision', precision_score(y_train,pred4 ))
print('recall', recall_score(y_train,pred4))
print('f1', f1_score(y_train,pred4))
confusion_matrix(y_train,pred4)

C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


robustscaler
('accuracy', 1.0)
('precision', 1.0)
('recall', 1.0)
('f1', 1.0)


array([[286,   0],
       [  0, 169]], dtype=int64)

In [30]:
## Test

In [55]:
# x_teste_norma0 = standardscales

pred = rf.predict(x_test_norma0)
print ('standardscales')
print('accuracy', accuracy_score(y_test,pred))
print('precision', precision_score(y_test,pred ))
print('recall', recall_score(y_test,pred))
print('f1', f1_score(y_test,pred))
confusion_matrix(y_test,pred)

standardscales
('accuracy', 0.956140350877193)
('precision', 0.975)
('recall', 0.9069767441860465)
('f1', 0.9397590361445783)


array([[70,  1],
       [ 4, 39]], dtype=int64)

In [32]:
# x_teste_norma1 = normalize

pred1 = rf1.predict(x_test_norma1)
print ('normalize')
print('accuracy', accuracy_score(y_test,pred1))
print('precision', precision_score(y_test,pred1 ))
print('recall', recall_score(y_test,pred1))
print('f1', f1_score(y_test,pred1))
confusion_matrix(y_test,pred1)

normalize
('accuracy', 0.9824561403508771)
('precision', 1.0)
('recall', 0.9534883720930233)
('f1', 0.9761904761904763)


array([[71,  0],
       [ 2, 41]], dtype=int64)

In [33]:
# x_teste_norma2 = maxabsscaler

pred2 = rf2.predict(x_test_norma2)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_test,pred2))
print('precision', precision_score(y_test,pred2 ))
print('recall', recall_score(y_test,pred2))
print('f1', f1_score(y_test,pred2))
confusion_matrix(y_test,pred2)

maxabsscaler
('accuracy', 0.8947368421052632)
('precision', 0.7818181818181819)
('recall', 1.0)
('f1', 0.8775510204081634)


array([[59, 12],
       [ 0, 43]], dtype=int64)

In [34]:
# x_teste_norma3 = minmaxscaler

pred3 = rf3.predict(x_test_norma3)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_test,pred3))
print('precision', precision_score(y_test,pred3 ))
print('recall', recall_score(y_test,pred3))
print('f1', f1_score(y_test,pred3))
confusion_matrix(y_test,pred3)

minmaxscaler
('accuracy', 0.9210526315789473)
('precision', 0.8269230769230769)
('recall', 1.0)
('f1', 0.9052631578947368)


array([[62,  9],
       [ 0, 43]], dtype=int64)

In [35]:
# x_teste_norma4 = robustscaler

pred4 = rf4.predict(x_test_norma4)
print ('robustscaler')
print('accuracy', accuracy_score(y_test,pred4))
print('precision', precision_score(y_test,pred4 ))
print('recall', recall_score(y_test,pred4))
print('f1', f1_score(y_test,pred4))
confusion_matrix(y_test,pred4)

robustscaler
('accuracy', 0.956140350877193)
('precision', 0.975)
('recall', 0.9069767441860465)
('f1', 0.9397590361445783)


array([[70,  1],
       [ 4, 39]], dtype=int64)

In [36]:
# notas standardscales

# # treino
# standardscales
# ('accuracy', 0.9978021978021978)
# ('precision', 1.0)
# ('recall', 0.9940828402366864)
# ('f1', 0.9970326409495549)

# array([[286,   0],
#        [  1, 168]], dtype=int64)

# # teste
# standardscales
# ('accuracy', 0.956140350877193)
# ('precision', 0.975)
# ('recall', 0.9069767441860465)
# ('f1', 0.9397590361445783)

# array([[70,  1],
#        [ 4, 39]], dtype=int64)



In [37]:
# notas normalize

# # treino 
# normalize
# ('accuracy', 1.0)
# ('precision', 1.0)
# ('recall', 1.0)
# ('f1', 1.0)

# array([[286,   0],
#        [  0, 169]], dtype=int64)

# # teste 
# normalize
# ('accuracy', 0.9824561403508771)
# ('precision', 1.0)
# ('recall', 0.9534883720930233)
# ('f1', 0.9761904761904763)

# array([[71,  0],
#        [ 2, 41]], dtype=int64)

In [38]:
# notas maxabsscaler

# # treino 
# maxabsscaler
# ('accuracy', 1.0)
# ('precision', 1.0)
# ('recall', 1.0)
# ('f1', 1.0)

# array([[286,   0],
#        [  0, 169]], dtype=int64)

# # teste 
# maxabsscaler
# ('accuracy', 0.8947368421052632)
# ('precision', 0.7818181818181819)
# ('recall', 1.0)
# ('f1', 0.8775510204081634)

# array([[59, 12],
#        [ 0, 43]], dtype=int64)

In [39]:
# notas minmaxscaler

# # treino 
# minmaxscaler
# ('accuracy', 0.9978021978021978)
# ('precision', 1.0)
# ('recall', 0.9940828402366864)
# ('f1', 0.9970326409495549)

# array([[286,   0],
#        [  1, 168]], dtype=int64)

# # teste 
# minmaxscaler
# ('accuracy', 0.9210526315789473)
# ('precision', 0.8269230769230769)
# ('recall', 1.0)
# ('f1', 0.9052631578947368)

# array([[62,  9],
#        [ 0, 43]], dtype=int64)

In [40]:
# notas robustscaler

# # treino 
# robustscaler
# ('accuracy', 1.0)
# ('precision', 1.0)
# ('recall', 1.0)
# ('f1', 1.0)

# array([[286,   0],
#        [  0, 169]], dtype=int64)

# # teste 
# robustscaler
# ('accuracy', 0.956140350877193)
# ('precision', 0.975)
# ('recall', 0.9069767441860465)
# ('f1', 0.9397590361445783)

# array([[70,  1],
#        [ 4, 39]], dtype=int64)


In [56]:
# notas melhores em cada categoria

# treino:
# accuracy = robustscaler e maxabsscaler e normalize (1) > minmaxscaler e standardscales (0.9978021978021978)
# precision = robustscaler e maxabsscaler e normalize e minmaxscaler e standardscales (1)
# recall = robustscaler e maxabsscaler e normalize (1) > minmaxscaler e standardscales (0.9940828402366864)
# f1 = robustscaler e maxabsscaler e normalize (1) > minmaxscaler e standardscales (0.9970326409495549)

# array = normalize e robustscaler e maxabsscaler (0) > minmaxscaler e standardscales (1)

# teste:
# accuracy = normalize (0.9824561403508771) > robustscaler e standardscales (0.956140350877193) > minmaxscaler (0.9210526315789473) > maxabsscaler (0.8947368421052632)
# precision = normalize (1) > standardscales e robustscaler (0.975) > minmaxscaler (0.8269230769230769) > maxabsscaler (0.7818181818181819)
# recall = maxabsscaler e minmaxscaler (1) > normalize (0.9534883720930233) > robustscaler e standardscales (0.9069767441860465)
# f1 = normalize (0.9761904761904763) > robustscaler e standardscales (0.9397590361445783) > minmaxscaler (0.9052631578947368) > maxabsscaler (0.8775510204081634)

# array = normalize (2) > standardscales e robustscaler (5[4,1]) > minmaxscaler (9) > maxabsscaler (12)

In [44]:
# one label enconder

In [49]:
# fazendo tudo isso com pca agora
pca = PCA()

In [50]:
pca.fit(x_train)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [51]:
pca.explained_variance_.round(3)

array([4.4405267e+05, 7.2980930e+03, 8.1612300e+02, 5.7337000e+01,
       3.9660000e+01, 2.8610000e+00, 1.7860000e+00, 3.8200000e-01,
       1.6400000e-01, 8.4000000e-02, 3.1000000e-02, 7.0000000e-03,
       3.0000000e-03, 2.0000000e-03, 1.0000000e-03, 1.0000000e-03,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00])

In [53]:
x_teste_pca = pca.transform(x_test)
x_train_pca = pca.transform(x_train)

x_test_norma0_pca = pd.DataFrame(standardscales.fit_transform(x_teste_pca))
x_train_norma0_pca = pd.DataFrame(standardscales.fit_transform(x_train_pca))


x_test_norma0_pca = pd.DataFrame(standardscales.fit_transform(x_teste_pca))
x_test_norma1_pca = pd.DataFrame(normalize.fit_transform(x_teste_pca))
x_test_norma2_pca = pd.DataFrame(maxabsscaler.fit_transform(x_teste_pca))
x_test_norma3_pca = pd.DataFrame(minmaxscaler.fit_transform(x_teste_pca))
x_test_norma4_pca = pd.DataFrame(robustscaler.fit_transform(x_teste_pca))

x_train_norma0_pca = pd.DataFrame(standardscales.fit_transform(x_train_pca))
x_train_norma1_pca = pd.DataFrame(normalize.fit_transform(x_train_pca))
x_train_norma2_pca = pd.DataFrame(maxabsscaler.fit_transform(x_train_pca))
x_train_norma3_pca = pd.DataFrame(minmaxscaler.fit_transform(x_train_pca))
x_train_norma4_pca = pd.DataFrame(robustscaler.fit_transform(x_train_pca))

In [60]:
# x_train_norma0 = standardscales

rf_pca = RandomForestClassifier()
rf_pca.fit(x_train_norma0_pca, y_train)

pred_pca = rf_pca.predict(x_train_norma0_pca)
print ('standardscales')
print('accuracy', accuracy_score(y_train,pred_pca))
print('precision', precision_score(y_train,pred_pca ))
print('recall', recall_score(y_train,pred_pca))
print('f1', f1_score(y_train,pred_pca))
confusion_matrix(y_train,pred_pca)


standardscales
('accuracy', 0.9978021978021978)
('precision', 1.0)
('recall', 0.9940828402366864)
('f1', 0.9970326409495549)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([[286,   0],
       [  1, 168]], dtype=int64)

In [59]:
# x_teste_norma0 = standardscales

pred_pca = rf_pca.predict(x_test_norma0_pca)
print ('standardscales')
print('accuracy', accuracy_score(y_test,pred_pca))
print('precision', precision_score(y_test,pred_pca ))
print('recall', recall_score(y_test,pred_pca))
print('f1', f1_score(y_test,pred_pca))
confusion_matrix(y_test,pred_pca)

standardscales
('accuracy', 0.9385964912280702)
('precision', 0.9090909090909091)
('recall', 0.9302325581395349)
('f1', 0.9195402298850575)


array([[67,  4],
       [ 3, 40]], dtype=int64)

In [61]:
# x_train_norma1 = normalize

rf1_pca = RandomForestClassifier()
rf1_pca.fit(x_train_norma1_pca, y_train)

pred1_pca = rf1_pca.predict(x_train_norma1_pca)
print ('normalize')
print('accuracy', accuracy_score(y_train,pred1_pca))
print('precision', precision_score(y_train,pred1_pca ))
print('recall', recall_score(y_train,pred1_pca))
print('f1', f1_score(y_train,pred1_pca))
confusion_matrix(y_train,pred1_pca)

normalize
('accuracy', 0.9956043956043956)
('precision', 0.9940828402366864)
('recall', 0.9940828402366864)
('f1', 0.9940828402366864)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([[285,   1],
       [  1, 168]], dtype=int64)

In [62]:
# x_teste_norma1 = normalize

pred1_pca = rf1_pca.predict(x_test_norma1_pca)
print ('normalize')
print('accuracy', accuracy_score(y_test,pred1_pca))
print('precision', precision_score(y_test,pred1_pca ))
print('recall', recall_score(y_test,pred1_pca))
print('f1', f1_score(y_test,pred1_pca))
confusion_matrix(y_test,pred1_pca)

normalize
('accuracy', 0.9649122807017544)
('precision', 0.9534883720930233)
('recall', 0.9534883720930233)
('f1', 0.9534883720930233)


array([[69,  2],
       [ 2, 41]], dtype=int64)

In [63]:
# x_train_norma2 = maxabsscaler

rf2_pca = RandomForestClassifier()
rf2_pca.fit(x_train_norma2_pca, y_train)

pred2_pca = rf2_pca.predict(x_train_norma2_pca)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_train,pred2_pca))
print('precision', precision_score(y_train,pred2_pca ))
print('recall', recall_score(y_train,pred2_pca))
print('f1', f1_score(y_train,pred2_pca))
confusion_matrix(y_train,pred2_pca)

maxabsscaler
('accuracy', 0.9978021978021978)
('precision', 1.0)
('recall', 0.9940828402366864)
('f1', 0.9970326409495549)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([[286,   0],
       [  1, 168]], dtype=int64)

In [64]:
# x_teste_norma2 = maxabsscaler

pred2_pca = rf2_pca.predict(x_test_norma2_pca)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_test,pred2_pca))
print('precision', precision_score(y_test,pred2_pca ))
print('recall', recall_score(y_test,pred2_pca))
print('f1', f1_score(y_test,pred2_pca))
confusion_matrix(y_test,pred2_pca)

maxabsscaler
('accuracy', 0.9122807017543859)
('precision', 0.8666666666666667)
('recall', 0.9069767441860465)
('f1', 0.8863636363636364)


array([[65,  6],
       [ 4, 39]], dtype=int64)

In [65]:
# x_train_norma3 = minmaxscaler

rf3_pca = RandomForestClassifier()
rf3_pca.fit(x_train_norma3_pca, y_train)

pred3_pca = rf3_pca.predict(x_train_norma3_pca)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_train,pred3_pca))
print('precision', precision_score(y_train,pred3_pca ))
print('recall', recall_score(y_train,pred3_pca))
print('f1', f1_score(y_train,pred3_pca))
confusion_matrix(y_train,pred3_pca)

minmaxscaler
('accuracy', 0.9934065934065934)
('precision', 1.0)
('recall', 0.9822485207100592)
('f1', 0.9910447761194029)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([[286,   0],
       [  3, 166]], dtype=int64)

In [66]:
# x_teste_norma3 = minmaxscaler

pred3_pca = rf3_pca.predict(x_test_norma3_pca)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_test,pred3_pca))
print('precision', precision_score(y_test,pred3_pca ))
print('recall', recall_score(y_test,pred3_pca))
print('f1', f1_score(y_test,pred3_pca))
confusion_matrix(y_test,pred3_pca)

minmaxscaler
('accuracy', 0.6842105263157895)
('precision', 0.547945205479452)
('recall', 0.9302325581395349)
('f1', 0.689655172413793)


array([[38, 33],
       [ 3, 40]], dtype=int64)

In [68]:
# x_train_norma4 = robustscaler

rf4_pca = RandomForestClassifier()
rf4_pca.fit(x_train_norma4_pca, y_train)

pred4_pca = rf4_pca.predict(x_train_norma4_pca)
print ('robustscaler')
print('accuracy', accuracy_score(y_train,pred4_pca))
print('precision', precision_score(y_train,pred4_pca ))
print('recall', recall_score(y_train,pred4_pca))
print('f1', f1_score(y_train,pred4_pca))
confusion_matrix(y_train,pred4_pca)

robustscaler
('accuracy', 0.9978021978021978)
('precision', 0.9941176470588236)
('recall', 1.0)
('f1', 0.9970501474926253)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([[285,   1],
       [  0, 169]], dtype=int64)

In [69]:
# x_teste_norma4 = robustscaler

pred4_pca = rf4_pca.predict(x_test_norma4_pca)
print ('robustscaler')
print('accuracy', accuracy_score(y_test,pred4_pca))
print('precision', precision_score(y_test,pred4_pca ))
print('recall', recall_score(y_test,pred4_pca))
print('f1', f1_score(y_test,pred4_pca))
confusion_matrix(y_test,pred4_pca)

robustscaler
('accuracy', 0.9473684210526315)
('precision', 0.9743589743589743)
('recall', 0.8837209302325582)
('f1', 0.9268292682926831)


array([[70,  1],
       [ 5, 38]], dtype=int64)

In [70]:
# notas standardscales com pca

# # treino
# standardscales
# ('accuracy', 0.9978021978021978)
# ('precision', 1.0)
# ('recall', 0.9940828402366864)
# ('f1', 0.9970326409495549)

# array([[286,   0],
#        [  1, 168]], dtype=int64)

# # teste
# standardscales
# ('accuracy', 0.9385964912280702)
# ('precision', 0.9090909090909091)
# ('recall', 0.9302325581395349)
# ('f1', 0.9195402298850575)

# array([[67,  4],
#        [ 3, 40]], dtype=int64)


In [71]:
# notas normalize com pca

# # treino 
# normalize
# ('accuracy', 0.9956043956043956)
# ('precision', 0.9940828402366864)
# ('recall', 0.9940828402366864)
# ('f1', 0.9940828402366864)

# array([[285,   1],
#        [  1, 168]], dtype=int64)

# # teste 
# normalize
# ('accuracy', 0.9649122807017544)
# ('precision', 0.9534883720930233)
# ('recall', 0.9534883720930233)
# ('f1', 0.9534883720930233)

# array([[69,  2],
#        [ 2, 41]], dtype=int64)

In [72]:
# notas maxabsscaler com pca

# # treino 
# maxabsscaler
# ('accuracy', 0.9978021978021978)
# ('precision', 1.0)
# ('recall', 0.9940828402366864)
# ('f1', 0.9970326409495549)

# array([[286,   0],
#        [  1, 168]], dtype=int64)

# # teste 
# maxabsscaler
# ('accuracy', 0.9122807017543859)
# ('precision', 0.8666666666666667)
# ('recall', 0.9069767441860465)
# ('f1', 0.8863636363636364)

# array([[65,  6],
#        [ 4, 39]], dtype=int64)

In [73]:
# notas minmaxscaler com pca

# # treino 
# minmaxscaler
# ('accuracy', 0.9934065934065934)
# ('precision', 1.0)
# ('recall', 0.9822485207100592)
# ('f1', 0.9910447761194029)

# array([[286,   0],
#        [  3, 166]], dtype=int64)

# # teste 
# minmaxscaler
# ('accuracy', 0.6842105263157895)
# ('precision', 0.547945205479452)
# ('recall', 0.9302325581395349)
# ('f1', 0.689655172413793)

# array([[38, 33],
#        [ 3, 40]], dtype=int64)

In [75]:
# notas robustscaler com pca

# # treino 
# robustscaler
# ('accuracy', 0.9978021978021978)
# ('precision', 0.9941176470588236)
# ('recall', 1.0)
# ('f1', 0.9970501474926253)

# array([[285,   1],
#        [  0, 169]], dtype=int64)

# # teste 
# robustscaler
# ('accuracy', 0.9473684210526315)
# ('precision', 0.9743589743589743)
# ('recall', 0.8837209302325582)
# ('f1', 0.9268292682926831)

# array([[70,  1],
#        [ 5, 38]], dtype=int64)

In [ ]:
# notas melhores em cada categoria com pca

# treino:
# accuracy = standardscales e robustscaler e maxabsscaler (0.9978021978021978) > normalize (0.9956043956043956) > minmaxscaler (0.9934065934065934)
# precision = standardscales e minmaxscaler e maxabsscaler (1) > robustscaler (0.9941176470588236) > normalize (0.9940828402366864)
# recall = robustscaler (1) > minmaxscaler (0.9822485207100592) > maxabsscaler e normalize e standardscales (0.9940828402366864)
# f1 = standardscales e robustscaler e maxabsscaler (0.9970501474926253) > normalize (0.9940828402366864) > minmaxscaler (0.9910447761194029)

# array = robustscaler e maxabsscaler e standardscales (1) > normalize(2) > minmaxscaler (3)

# teste:
# accuracy = 
# precision = 
# recall = 
# f1 = 

# array = normalize (4) > robustscaler (6) > standardscales (7) > maxabsscaler (10) > minmaxscaler (36)