In [1]:
# imports 
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,Normalizer,MaxAbsScaler,MinMaxScaler,RobustScaler
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
import matplotlib.pyplot as pl
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.naive_bayes import GaussianNB

# enviar para o email de igorlpa90@gmail.com

C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


# Exercicio modulo 4 pos

## Carrega arquivo de dados

In [2]:
df = pd.read_csv('Reaction_Network.data',header=None)

## verificando dados do database

In [3]:
df.head(10)

0   1   2   3            4     5         6         7         8   \
0  aac00010   1  15   8  0.086580087   506  5.905138  2.260870  0.102767   
1  aac00020   1   7   5  0.091503268   342  3.309942  2.526316  0.140351   
2  aac00030   2   8   1  0.177489177   386  3.191710  2.434783  0.110672   
3  aac00040   5   5   1  0.087719298    92  2.304348  1.500000  0.078947   
4  aac00051   2   5   1  0.196969697   112  2.446429  2.000000  0.166667   
5  aac00052   3   7   1  0.317028986   424  3.009434  2.000000  0.083333   
6  aac00061   1   7   4  0.182788051  1482  3.700405  2.410256  0.063428   
7  aac00071   3   8   1  0.161904762   942  3.397028  2.486486  0.069069   
8  aac00072   1   3   2  0.416666667    20  1.600000  2.000000  0.500000   
9  aac00130   2   6   2  0.115384615    84  2.476190  1.714286  0.131868   

         9  ...         19        20        21         22   23        24  \
0  0.350401 ...   0.423671  0.233578  0.672991  11.739130  0.0  0.175792   
1  0.324091 ...   0.442857  0.135879  0.670008   5.789474  0.0  0.307019   
2  0.683255 ...   0.264447  0.150775  0.736842   5.478261  0.0  0.387645   
3  0.447214 ...   0.183333  0.184762  0.794286   2.900000  0.0  0.616221   
4  0.554700 ...   0.270192  0.138462  0.750769   3.538462  0.0  0.509972   
5  0.787401 ...   0.313481  0.089684  0.756571   4.640000  0.0  0.451110   
6  0.494652 ...   0.433191  0.072984  0.614228   5.871795  0.0  0.280857   
7  0.550176 ...   0.347668  0.124076  0.719144   5.810811  0.0  0.382379   
8  0.316228 ...   0.633333  0.200000  0.800000   2.400000  0.0  0.640952   
9  0.408248 ...   0.261905  0.295238  0.700397   4.071429  0.0  0.423958   

         25        26  27   28  
0  5.905138  0.181159  23   44  
1  3.309942  0.070175  19   44  
2  2.974828  0.124638  23   56  
3  1.948571  0.000000  20   26  
4  2.246154  0.000000  13   22  
5  2.704000  0.054444  25   43  
6  3.700405  0.000000  39   95  
7  3.084685  0.000000  37  102  
8  1.600000  0.000000   5    8  
9  2.476190  0.000000  14   14  

[10 rows x 29 columns]

In [4]:
df.describe()

1             2             3             5             6   \
count  65554.000000  65554.000000  65554.000000  65554.000000  65554.000000   
mean       3.077478      4.292797      1.436297    134.300882      2.095586   
std        2.648381      3.264375      1.094364    307.832320      1.147462   
min        1.000000      1.000000      1.000000      2.000000      1.000000   
25%        2.000000      2.000000      1.000000     10.000000      1.250000   
50%        2.000000      3.000000      1.000000     34.000000      1.705882   
75%        4.000000      6.000000      1.000000    132.000000      2.617146   
max       39.000000     46.000000     13.000000  23420.000000     15.972929   

                 7             8             9             10            11  \
count  65554.000000  65554.000000  65554.000000  65554.000000  65554.000000   
mean       1.557635      0.222199      0.375681      0.016887      0.027611   
std        0.444173      0.188456      0.206778      0.141057      0.217744   
min        0.666667      0.008210      0.000000      0.000000      0.000000   
25%        1.200000      0.100000      0.319438      0.000000      0.000000   
50%        1.500000      0.153846      0.353553      0.000000      0.000000   
75%        1.833333      0.300000      0.492548      0.000000      0.000000   
max        3.440000      1.000000      1.796203      3.000000      4.000000   

           ...                 19            20            21            22  \
count      ...       65554.000000  65554.000000  6.555400e+04  65554.000000   
mean       ...           0.169358      0.175088  1.093830e+08      2.998901   
std        ...           0.175356      0.100871  1.038254e+09      2.240179   
min        ...           0.000000      0.000000  5.437276e-01      0.666667   
25%        ...           0.000000      0.114583  7.455556e-01      1.400000   
50%        ...           0.150000      0.185185  8.214286e-01      2.235294   
75%        ...           0.284308      0.244444  9.000000e-01      3.800000   
max        ...           1.000000      0.333333  3.074457e+10     25.034091   

                 23            24            25            26            27  \
count  65554.000000  65554.000000  65554.000000  65554.000000  65554.000000   
mean       0.001737      0.671134      1.948226      0.030610     13.696189   
std        0.014659      0.230285      1.038546      0.087377     11.076390   
min        0.000000      0.102206      0.666667      0.000000      2.000000   
25%        0.000000      0.492177      1.200000      0.000000      6.000000   
50%        0.000000      0.693933      1.592157      0.000000     11.000000   
75%        0.000000      0.866667      2.352381      0.000000     18.000000   
max        0.666667      1.000000     12.667032      1.000000    232.000000   

                 28  
count  65554.000000  
mean      17.021341  
std       18.518104  
min        1.000000  
25%        5.000000  
50%       11.000000  
75%       22.000000  
max      444.000000  

[8 rows x 27 columns]

In [5]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
dtype: int64

In [6]:
df.dtypes

0      object
1       int64
2       int64
3       int64
4      object
5       int64
6     float64
7     float64
8     float64
9     float64
10      int64
11      int64
12      int64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
24    float64
25    float64
26    float64
27      int64
28      int64
dtype: object

In [7]:
# verificando o que tem dentro da coluna de string
df.groupby(4).count()

0     1     2     3     5     6     7     8     9     10  ...   \
4                                                                        ...    
0            9175  9175  9175  9175  9175  9175  9175  9175  9175  9175  ...    
0.010734463     1     1     1     1     1     1     1     1     1     1  ...    
0.011278195     4     4     4     4     4     4     4     4     4     4  ...    
0.011689071    18    18    18    18    18    18    18    18    18    18  ...    
0.011879804     2     2     2     2     2     2     2     2     2     2  ...    
0.012337662    20    20    20    20    20    20    20    20    20    20  ...    
0.01254902      2     2     2     2     2     2     2     2     2     2  ...    
0.012987013     3     3     3     3     3     3     3     3     3     3  ...    
0.013062409    28    28    28    28    28    28    28    28    28    28  ...    
0.013877551    15    15    15    15    15    15    15    15    15    15  ...    
0.014141414     1     1     1     1     1     1     1     1     1     1  ...    
0.014492754     2     2     2     2     2     2     2     2     2     2  ...    
0.01480111      7     7     7     7     7     7     7     7     7     7  ...    
0.015810277     3     3     3     3     3     3     3     3     3     3  ...    
0.015856237     7     7     7     7     7     7     7     7     7     7  ...    
0.015873016     1     1     1     1     1     1     1     1     1     1  ...    
0.016194332     1     1     1     1     1     1     1     1     1     1  ...    
0.016666667     1     1     1     1     1     1     1     1     1     1  ...    
0.017073171     4     4     4     4     4     4     4     4     4     4  ...    
0.017460317     2     2     2     2     2     2     2     2     2     2  ...    
0.018461538     1     1     1     1     1     1     1     1     1     1  ...    
0.018492176     4     4     4     4     4     4     4     4     4     4  ...    
0.018939394     2     2     2     2     2     2     2     2     2     2  ...    
0.019047619     1     1     1     1     1     1     1     1     1     1  ...    
0.019230769     1     1     1     1     1     1     1     1     1     1  ...    
0.019512195     1     1     1     1     1     1     1     1     1     1  ...    
0.019914651     1     1     1     1     1     1     1     1     1     1  ...    
0.020168067    10    10    10    10    10    10    10    10    10    10  ...    
0.020242915     1     1     1     1     1     1     1     1     1     1  ...    
0.020634921     1     1     1     1     1     1     1     1     1     1  ...    
...           ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    
0.683006536     3     3     3     3     3     3     3     3     3     3  ...    
0.685714286     1     1     1     1     1     1     1     1     1     1  ...    
0.689393939     2     2     2     2     2     2     2     2     2     2  ...    
0.694444444     5     5     5     5     5     5     5     5     5     5  ...    
0.7            54    54    54    54    54    54    54    54    54    54  ...    
0.704545455     1     1     1     1     1     1     1     1     1     1  ...    
0.714285714     6     6     6     6     6     6     6     6     6     6  ...    
0.717948718     1     1     1     1     1     1     1     1     1     1  ...    
0.71969697      1     1     1     1     1     1     1     1     1     1  ...    
0.722222222     2     2     2     2     2     2     2     2     2     2  ...    
0.733333333     3     3     3     3     3     3     3     3     3     3  ...    
0.755555556     1     1     1     1     1     1     1     1     1     1  ...    
0.761904762     8     8     8     8     8     8     8     8     8     8  ...    
0.763636364     2     2     2     2     2     2     2     2     2     2  ...    
0.766666667     3     3     3     3     3     3     3     3     3     3  ...    
0.787878788     1     1     1     1     1     1     1     1     1     1  ...    
0.8             4     4     4     4     4     

## tratando dados faltando

In [8]:
# removendo valores ruidosos
df[4] = df[4].replace('?',np.nan)

In [9]:
df[4]

0        0.086580087
1        0.091503268
2        0.177489177
3        0.087719298
4        0.196969697
5        0.317028986
6        0.182788051
7        0.161904762
8        0.416666667
9        0.115384615
10       0.058039216
11       0.086021505
12       0.192982456
13       0.081792319
14        0.05952381
15               0.2
16              0.05
17       0.104761905
18       0.111111111
19       0.077235772
20       0.115384615
21       0.133333333
22       0.133333333
23       0.076923077
24       0.067028986
25                 1
26       0.076923077
27       0.065789474
28               NaN
29               NaN
            ...     
65524              0
65525              0
65526         0.1125
65527              0
65528              0
65529              0
65530              0
65531    0.428571429
65532    0.142857143
65533         0.1875
65534    0.166666667
65535    0.242424242
65536    0.166666667
65537    0.188888889
65538    0.113636364
65539    0.122807018
65540    0.06

In [10]:
df.groupby(4).count()

0     1     2     3     5     6     7     8     9     10  ...   \
4                                                                        ...    
0            9175  9175  9175  9175  9175  9175  9175  9175  9175  9175  ...    
0.010734463     1     1     1     1     1     1     1     1     1     1  ...    
0.011278195     4     4     4     4     4     4     4     4     4     4  ...    
0.011689071    18    18    18    18    18    18    18    18    18    18  ...    
0.011879804     2     2     2     2     2     2     2     2     2     2  ...    
0.012337662    20    20    20    20    20    20    20    20    20    20  ...    
0.01254902      2     2     2     2     2     2     2     2     2     2  ...    
0.012987013     3     3     3     3     3     3     3     3     3     3  ...    
0.013062409    28    28    28    28    28    28    28    28    28    28  ...    
0.013877551    15    15    15    15    15    15    15    15    15    15  ...    
0.014141414     1     1     1     1     1     1     1     1     1     1  ...    
0.014492754     2     2     2     2     2     2     2     2     2     2  ...    
0.01480111      7     7     7     7     7     7     7     7     7     7  ...    
0.015810277     3     3     3     3     3     3     3     3     3     3  ...    
0.015856237     7     7     7     7     7     7     7     7     7     7  ...    
0.015873016     1     1     1     1     1     1     1     1     1     1  ...    
0.016194332     1     1     1     1     1     1     1     1     1     1  ...    
0.016666667     1     1     1     1     1     1     1     1     1     1  ...    
0.017073171     4     4     4     4     4     4     4     4     4     4  ...    
0.017460317     2     2     2     2     2     2     2     2     2     2  ...    
0.018461538     1     1     1     1     1     1     1     1     1     1  ...    
0.018492176     4     4     4     4     4     4     4     4     4     4  ...    
0.018939394     2     2     2     2     2     2     2     2     2     2  ...    
0.019047619     1     1     1     1     1     1     1     1     1     1  ...    
0.019230769     1     1     1     1     1     1     1     1     1     1  ...    
0.019512195     1     1     1     1     1     1     1     1     1     1  ...    
0.019914651     1     1     1     1     1     1     1     1     1     1  ...    
0.020168067    10    10    10    10    10    10    10    10    10    10  ...    
0.020242915     1     1     1     1     1     1     1     1     1     1  ...    
0.020634921     1     1     1     1     1     1     1     1     1     1  ...    
...           ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    
0.678571429     3     3     3     3     3     3     3     3     3     3  ...    
0.683006536     3     3     3     3     3     3     3     3     3     3  ...    
0.685714286     1     1     1     1     1     1     1     1     1     1  ...    
0.689393939     2     2     2     2     2     2     2     2     2     2  ...    
0.694444444     5     5     5     5     5     5     5     5     5     5  ...    
0.7            54    54    54    54    54    54    54    54    54    54  ...    
0.704545455     1     1     1     1     1     1     1     1     1     1  ...    
0.714285714     6     6     6     6     6     6     6     6     6     6  ...    
0.717948718     1     1     1     1     1     1     1     1     1     1  ...    
0.71969697      1     1     1     1     1     1     1     1     1     1  ...    
0.722222222     2     2     2     2     2     2     2     2     2     2  ...    
0.733333333     3     3     3     3     3     3     3     3     3     3  ...    
0.755555556     1     1     1     1     1     1     1     1     1     1  ...    
0.761904762     8     8     8     8     8     8     8     8     8     8  ...    
0.763636364     2     2     2     2     2     2     2     2     2     2  ...    
0.766666667     3     3     3     3     3     3     3     3     3     3  ...    
0.787878788     1     1     1     1     1     

In [11]:
# transforma coluna object para float e subistitui nan pela medias
df[4] = df[4].astype(float)
df[4] = df[4].fillna(str(df[4].mean()))
df.groupby(4).count()

0     1     2     3     5     6     7     8     9     10  \
4                                                                            
0.0             9175  9175  9175  9175  9175  9175  9175  9175  9175  9175   
0.010734463        1     1     1     1     1     1     1     1     1     1   
0.011278195        4     4     4     4     4     4     4     4     4     4   
0.011689071       18    18    18    18    18    18    18    18    18    18   
0.011879804        2     2     2     2     2     2     2     2     2     2   
0.012337662       20    20    20    20    20    20    20    20    20    20   
0.01254902         2     2     2     2     2     2     2     2     2     2   
0.012987013        3     3     3     3     3     3     3     3     3     3   
0.013062409       28    28    28    28    28    28    28    28    28    28   
0.013877551       15    15    15    15    15    15    15    15    15    15   
0.014141414        1     1     1     1     1     1     1     1     1     1   
0.014492754        2     2     2     2     2     2     2     2     2     2   
0.01480111         7     7     7     7     7     7     7     7     7     7   
0.015810277        3     3     3     3     3     3     3     3     3     3   
0.015856237        7     7     7     7     7     7     7     7     7     7   
0.015873016        1     1     1     1     1     1     1     1     1     1   
0.016194332        1     1     1     1     1     1     1     1     1     1   
0.016666667        1     1     1     1     1     1     1     1     1     1   
0.017073171        4     4     4     4     4     4     4     4     4     4   
0.017460317        2     2     2     2     2     2     2     2     2     2   
0.018461538        1     1     1     1     1     1     1     1     1     1   
0.018492176        4     4     4     4     4     4     4     4     4     4   
0.018939394        2     2     2     2     2     2     2     2     2     2   
0.019047619        1     1     1     1     1     1     1     1     1     1   
0.019230769        1     1     1     1     1     1     1     1     1     1   
0.019512195        1     1     1     1     1     1     1     1     1     1   
0.019914651        1     1     1     1     1     1     1     1     1     1   
0.020168067       10    10    10    10    10    10    10    10    10    10   
0.020242915        1     1     1     1     1     1     1     1     1     1   
0.020634921        1     1     1     1     1     1     1     1     1     1   
...              ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
0.683006536        3     3     3     3     3     3     3     3     3     3   
0.685714286        1     1     1     1     1     1     1     1     1     1   
0.689393939        2     2     2     2     2     2     2     2     2     2   
0.694444444        5     5     5     5     5     5     5     5     5     5   
0.7               54    54    54    54    54    54    54    54    54    54   
0.704545455        1     1     1     1     1     1     1     1     1     1   
0.714285714        6     6     6     6     6     6     6     6     6     6   
0.717948718        1     1     1     1     1     1     1     1     1     1   
0.71969697         1     1     1     1     1     1     1     1     1     1   
0.722222222        2     2     2     2     2     2     2     2     2     2   
0.733333333        3     3     3     3     3     3     3     3     3     3   
0.755555556        1     1     1     1     1     1     1     1     1     1   
0.761904762        8     8     8     8     8     8     8     8     8     8   
0.763636364        2     2     2     2     2     2     2     2     2     2   
0.766666667        3     3     3     3     3     3     3     3     3     3   
0.787878788        1     1     1     1     1     1     1     1     1     1   
0.8                4     4     4     4     4     4     4     4     4     4   
0.803571429        2     2     2     2     2     2     2     2     2     2   
0.805555556        1     1     1     1  

## Separando o x e o y

In [12]:
# verificando o que temos
df.head()

0   1   2   3          4    5         6         7         8   \
0  aac00010   1  15   8  0.0865801  506  5.905138  2.260870  0.102767   
1  aac00020   1   7   5  0.0915033  342  3.309942  2.526316  0.140351   
2  aac00030   2   8   1   0.177489  386  3.191710  2.434783  0.110672   
3  aac00040   5   5   1  0.0877193   92  2.304348  1.500000  0.078947   
4  aac00051   2   5   1    0.19697  112  2.446429  2.000000  0.166667   

         9  ...        19        20        21         22   23        24  \
0  0.350401 ...  0.423671  0.233578  0.672991  11.739130  0.0  0.175792   
1  0.324091 ...  0.442857  0.135879  0.670008   5.789474  0.0  0.307019   
2  0.683255 ...  0.264447  0.150775  0.736842   5.478261  0.0  0.387645   
3  0.447214 ...  0.183333  0.184762  0.794286   2.900000  0.0  0.616221   
4  0.554700 ...  0.270192  0.138462  0.750769   3.538462  0.0  0.509972   

         25        26  27  28  
0  5.905138  0.181159  23  44  
1  3.309942  0.070175  19  44  
2  2.974828  0.124638  23  56  
3  1.948571  0.000000  20  26  
4  2.246154  0.000000  13  22  

[5 rows x 29 columns]

In [13]:
# ! tive que diminuir pois esta travando a maquina
# separando o Y e o X
Y = pd.DataFrame(df[0][:1000])
X = pd.DataFrame(df.iloc[:,1:][:1000])

# Transformando o Y em labels
encoder_y = LabelEncoder() 
Y = pd.DataFrame( encoder_y.fit_transform(Y))

# verificando o Y e X
print(Y.shape,X.shape)
print(Y.dtypes)
print ' '
print(X.dtypes)

((1000, 1), (1000, 28))
0    int64
dtype: object
 
1       int64
2       int64
3       int64
4      object
5       int64
6     float64
7     float64
8     float64
9     float64
10      int64
11      int64
12      int64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
24    float64
25    float64
26    float64
27      int64
28      int64
dtype: object


C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Separando os dados de teste e de treino

In [14]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42 )

In [15]:
# verificando a separacao
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

((800, 28), (800, 1))
((200, 28), (200, 1))


## analisando dados de treino e de teste

In [16]:
x_train.describe()

1           2          3             5           6           7   \
count  800.00000  800.000000  800.00000    800.000000  800.000000  800.000000   
mean     3.21250    4.557500    1.45625    203.500000    2.174002    1.549791   
std      3.45431    3.908425    1.16395   1237.575853    1.349111    0.432916   
min      1.00000    1.000000    1.00000      2.000000    1.000000    1.000000   
25%      2.00000    2.000000    1.00000     10.000000    1.285714    1.228632   
50%      2.00000    3.000000    1.00000     38.000000    1.787594    1.500000   
75%      4.00000    6.000000    1.00000    132.500000    2.751786    1.820158   
max     39.00000   46.000000    8.00000  23420.000000   15.972929    3.047619   

               8           9           10          11     ...              19  \
count  800.000000  800.000000  800.000000  800.000000     ...      800.000000   
mean     0.221282    0.368883    0.022500    0.030000     ...        0.169030   
std      0.191093    0.202231    0.156603    0.227298     ...        0.172761   
min      0.008210    0.000000    0.000000    0.000000     ...        0.000000   
25%      0.100000    0.316228    0.000000    0.000000     ...        0.000000   
50%      0.145455    0.355312    0.000000    0.000000     ...        0.157999   
75%      0.285714    0.480384    0.000000    0.000000     ...        0.277369   
max      1.000000    1.185854    2.000000    3.000000     ...        1.000000   

               20            21          22          23          24  \
count  800.000000  8.000000e+02  800.000000  800.000000  800.000000   
mean     0.176620  1.536264e+08    3.129201    0.002216    0.664357   
std      0.102219  1.171150e+09    2.468029    0.018087    0.233386   
min      0.000000  5.875000e-01    1.000000    0.000000    0.166873   
25%      0.117647  7.466667e-01    1.442708    0.000000    0.470909   
50%      0.184881  8.219298e-01    2.350000    0.000000    0.672806   
75%      0.249152  9.000000e-01    4.011905    0.000000    0.850000   
max      0.333333  1.537229e+10   23.254310    0.250000    1.000000   

               25          26          27          28  
count  800.000000  800.000000  800.000000  800.000000  
mean     2.001309    0.026869   14.451250   18.471250  
std      1.134444    0.072927   16.999304   31.845397  
min      1.000000    0.000000    2.000000    1.000000  
25%      1.222222    0.000000    6.000000    5.000000  
50%      1.639957    0.000000   11.000000   11.000000  
75%      2.456654    0.000000   19.000000   22.000000  
max     11.050855    0.600000  232.000000  444.000000  

[8 rows x 27 columns]

In [17]:
x_test.describe()

1           2           3            5           6   \
count  200.000000  200.000000  200.000000   200.000000  200.000000   
mean     3.050000    4.485000    1.410000   129.100000    2.158283   
std      2.378188    3.713316    1.143872   282.857192    1.286250   
min      1.000000    1.000000    1.000000     2.000000    1.000000   
25%      2.000000    2.000000    1.000000    12.000000    1.315559   
50%      2.000000    3.000000    1.000000    30.000000    1.689291   
75%      4.000000    6.000000    1.000000   123.000000    2.465303   
max     18.000000   20.000000    8.000000  2002.000000    7.590955   

               7           8           9           10         11     ...      \
count  200.000000  200.000000  200.000000  200.000000  200.00000     ...       
mean     1.550756    0.217907    0.380705    0.015000    0.02500     ...       
std      0.416795    0.176096    0.196527    0.157796    0.23377     ...       
min      1.000000    0.025063    0.000000    0.000000    0.00000     ...       
25%      1.250000    0.099854    0.329325    0.000000    0.00000     ...       
50%      1.500000    0.166667    0.353553    0.000000    0.00000     ...       
75%      1.770898    0.285714    0.487473    0.000000    0.00000     ...       
max      2.857143    1.000000    1.013246    2.000000    3.00000     ...       

               19          20            21          22          23  \
count  200.000000  200.000000  2.000000e+02  200.000000  200.000000   
mean     0.173058    0.182107  7.852716e+07    3.111111    0.001562   
std      0.190704    0.096363  8.389893e+08    2.504192    0.014243   
min      0.000000    0.000000  5.857143e-01    1.000000    0.000000   
25%      0.000000    0.126852  7.500000e-01    1.500000    0.000000   
50%      0.135513    0.190476  8.236111e-01    2.142857    0.000000   
75%      0.296084    0.244439  8.948718e-01    3.600000    0.000000   
max      1.000000    0.333333  1.085103e+10   13.903846    0.176471   

               24          25          26         27          28  
count  200.000000  200.000000  200.000000  200.00000  200.000000  
mean     0.670014    1.991866    0.030441   13.32000   15.910000  
std      0.224757    1.137695    0.083419   10.32719   16.783633  
min      0.180032    1.000000    0.000000    2.00000    2.000000  
25%      0.508976    1.250000    0.000000    6.00000    5.000000  
50%      0.703968    1.535857    0.000000   10.00000   10.000000  
75%      0.833333    2.291185    0.000000   18.25000   21.000000  
max      1.000000    6.750874    0.583333   61.00000   99.000000  

[8 rows x 27 columns]

In [18]:
y_train.columns = ['label']
corr = pd.concat([x_train, y_train ], axis=1).corr()
corr.style.background_gradient(cmap='coolwarm')

## normalizando os dados utilizando os 5 tipos importados

In [19]:
# normalizando os dados de treino e de teste
standardscales = StandardScaler()
normalize = Normalizer()
maxabsscaler = MaxAbsScaler()
minmaxscaler = MinMaxScaler()
robustscaler = RobustScaler()

x_train_norma0 = pd.DataFrame(standardscales.fit_transform(x_train))
x_train_norma1 = pd.DataFrame(normalize.fit_transform(x_train))
x_train_norma2 = pd.DataFrame(maxabsscaler.fit_transform(x_train))
x_train_norma3 = pd.DataFrame(minmaxscaler.fit_transform(x_train))
x_train_norma4 = pd.DataFrame(robustscaler.fit_transform(x_train))

x_test_norma0 = pd.DataFrame(standardscales.fit_transform(x_test))
x_test_norma1 = pd.DataFrame(normalize.fit_transform(x_test))
x_test_norma2 = pd.DataFrame(maxabsscaler.fit_transform(x_test))
x_test_norma3 = pd.DataFrame(minmaxscaler.fit_transform(x_test))
x_test_norma4 = pd.DataFrame(robustscaler.fit_transform(x_test))

## verificando os dados normalizados de treino

In [20]:
x_train_norma0.describe()

0             1             2             3             4   \
count  8.000000e+02  8.000000e+02  8.000000e+02  8.000000e+02  8.000000e+02   
mean   3.049644e-16 -6.512152e-17 -1.167122e-16 -1.214306e-17  2.255141e-19   
std    1.000626e+00  1.000626e+00  1.000626e+00  1.000626e+00  1.000626e+00   
min   -6.409048e-01 -9.107825e-01 -3.922294e-01 -8.250439e-01 -1.629202e-01   
25%   -3.512303e-01 -6.547650e-01 -3.922294e-01 -5.624235e-01 -1.564519e-01   
50%   -3.512303e-01 -3.987474e-01 -3.922294e-01 -2.998032e-01 -1.338128e-01   
75%    2.281187e-01  3.693054e-01 -3.922294e-01  7.025277e-02 -5.740611e-02   
max    1.036673e+01  1.061001e+01  5.625537e+00  3.114261e+00  1.877139e+01   

                 5             6             7             8             9   \
count  8.000000e+02  8.000000e+02  8.000000e+02  8.000000e+02  8.000000e+02   
mean   3.004194e-16 -8.104628e-17  8.715251e-17  1.054712e-17 -4.961309e-17   
std    1.000626e+00  1.000626e+00  1.000626e+00  1.000626e+00  1.000626e+00   
min   -8.707488e-01 -1.270765e+00 -1.115713e+00 -1.825206e+00 -1.437656e-01   
25%   -6.588367e-01 -7.423130e-01 -6.350723e-01 -2.605339e-01 -1.437656e-01   
50%   -2.865963e-01 -1.150849e-01 -3.970578e-01 -6.714595e-02 -1.437656e-01   
75%    4.285375e-01  6.249157e-01  3.373867e-01  5.517016e-01 -1.437656e-01   
max    1.023456e+01  3.462020e+00  4.077614e+00  4.042315e+00  1.263540e+01   

           ...                 18            19            20            21  \
count      ...       8.000000e+02  8.000000e+02  8.000000e+02  8.000000e+02   
mean       ...      -2.891264e-16  2.140649e-16 -1.168857e-16 -2.289835e-17   
std        ...       1.000626e+00  1.000626e+00  1.000626e+00  1.000626e+00   
min        ...      -9.790143e-01 -1.728943e+00 -1.312577e-01 -8.632525e-01   
25%        ...      -9.790143e-01 -5.772915e-01 -1.312577e-01 -6.837630e-01   
50%        ...      -6.388813e-02  8.086355e-02 -1.312577e-01 -3.159152e-01   
75%        ...       6.274936e-01  7.100111e-01 -1.312577e-01  3.578792e-01   
max        ...       4.812947e+00  1.534069e+00  1.300275e+01  8.159424e+00   

                 22            23            24            25            26  \
count  8.000000e+02  8.000000e+02  8.000000e+02  8.000000e+02  8.000000e+02   
mean   6.149595e-16 -3.997497e-16  3.144013e-16 -5.152823e-16 -2.050443e-17   
std    1.000626e+00  1.000626e+00  1.000626e+00  1.000626e+00  1.000626e+00   
min   -1.225801e-01 -2.132930e+00 -8.831952e-01 -3.686683e-01 -7.329147e-01   
25%   -1.225801e-01 -8.293931e-01 -6.871862e-01 -3.686683e-01 -4.974637e-01   
50%   -1.225801e-01  3.622737e-02 -3.187268e-01 -3.686683e-01 -2.031500e-01   
75%   -1.225801e-01  7.959344e-01  4.016334e-01 -3.686683e-01  2.677519e-01   
max    1.370781e+01  1.439050e+00  7.982068e+00  7.863869e+00  1.280552e+01   

                 27  
count  8.000000e+02  
mean  -6.064593e-17  
std    1.000626e+00  
min   -5.489704e-01  
25%   -4.232849e-01  
50%   -2.347568e-01  
75%    1.108781e-01  
max    1.337069e+01  

[8 rows x 28 columns]

In [21]:
x_train_norma1.describe()

0             1             2           3             4   \
count  8.000000e+02  8.000000e+02  8.000000e+02  800.000000  8.000000e+02   
mean   1.008011e-01  8.928851e-02  4.734667e-02    0.012136  8.033535e-01   
std    9.615834e-02  5.993301e-02  4.560594e-02    0.028569  1.986451e-01   
min    1.517883e-10  2.602085e-10  6.505213e-11    0.000000  1.908196e-09   
25%    1.720865e-02  4.212096e-02  9.665269e-03    0.000269  6.923061e-01   
50%    6.763425e-02  7.834341e-02  2.904462e-02    0.001379  8.758235e-01   
75%    1.644187e-01  1.292491e-01  8.273910e-02    0.006492  9.621543e-01   
max    3.115010e-01  2.342929e-01  2.129811e-01    0.117146  9.968876e-01   

                 5             6             7           8             9   \
count  8.000000e+02  8.000000e+02  8.000000e+02  800.000000  8.000000e+02   
mean   5.716988e-02  5.319756e-02  1.583148e-02    0.009319  3.672735e-12   
std    4.710893e-02  4.918336e-02  2.885678e-02    0.011228  2.636616e-11   
min    1.415840e-10  7.589415e-11  6.899468e-12    0.000000  0.000000e+00   
25%    1.916081e-02  1.233177e-02  7.367362e-04    0.000915  0.000000e+00   
50%    4.214345e-02  3.532271e-02  3.228898e-03    0.004810  0.000000e+00   
75%    8.757810e-02  8.339262e-02  1.777552e-02    0.013266  0.000000e+00   
max    2.129811e-01  2.129811e-01  2.129811e-01    0.041418  2.493665e-10   

           ...               18          19          20            21  \
count      ...       800.000000  800.000000  800.000000  8.000000e+02   
mean       ...         0.002731    0.006231    0.059925  6.913852e-02   
std        ...         0.006574    0.009818    0.145137  5.292214e-02   
min        ...         0.000000    0.000000    0.000032  1.517883e-10   
25%        ...         0.000000    0.000378    0.005580  2.654600e-02   
50%        ...         0.000825    0.002118    0.021543  5.315964e-02   
75%        ...         0.002569    0.007115    0.071852  9.948402e-02   
max        ...         0.068154    0.039049    1.000000  2.129811e-01   

                 22            23            24          25            26  \
count  8.000000e+02  8.000000e+02  8.000000e+02  800.000000  8.000000e+02   
mean   3.049319e-13  3.636846e-02  5.533791e-02    0.000312  2.759810e-01   
std    2.256746e-12  4.351374e-02  4.756651e-02    0.001584  1.786014e-01   
min    0.000000e+00  2.913109e-11  9.757820e-11    0.000000  5.312591e-10   
25%    0.000000e+00  3.327400e-03  1.705127e-02    0.000000  1.185030e-01   
50%    0.000000e+00  1.598470e-02  3.746943e-02    0.000000  2.597586e-01   
75%    0.000000e+00  5.899383e-02  8.610126e-02    0.000000  4.133590e-01   
max    3.252607e-11  2.129811e-01  2.129811e-01    0.020329  6.230020e-01   

                 27  
count  8.000000e+02  
mean   2.438426e-01  
std    1.245880e-01  
min    6.830474e-10  
25%    1.431731e-01  
50%    2.473159e-01  
75%    3.220303e-01  
max    7.369931e-01  

[8 rows x 28 columns]

In [22]:
x_train_norma2.describe()

0           1           2           3           4           5   \
count  800.000000  800.000000  800.000000  800.000000  800.000000  800.000000   
mean     0.082372    0.099076    0.182031    0.209439    0.008689    0.136105   
std      0.088572    0.084966    0.145494    0.254011    0.052843    0.084462   
min      0.025641    0.021739    0.125000    0.000000    0.000085    0.062606   
25%      0.051282    0.043478    0.125000    0.066667    0.000427    0.080493   
50%      0.051282    0.065217    0.125000    0.133333    0.001623    0.111914   
75%      0.102564    0.130435    0.125000    0.227273    0.005658    0.172278   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               6           7           8           9      ...              18  \
count  800.000000  800.000000  800.000000  800.000000     ...      800.000000   
mean     0.508525    0.221282    0.311069    0.011250     ...        0.169030   
std      0.142051    0.191093    0.170536    0.078301     ...        0.172761   
min      0.328125    0.008210    0.000000    0.000000     ...        0.000000   
25%      0.403145    0.100000    0.266667    0.000000     ...        0.000000   
50%      0.492187    0.145455    0.299626    0.000000     ...        0.157999   
75%      0.597239    0.285714    0.405096    0.000000     ...        0.277369   
max      1.000000    1.000000    1.000000    1.000000     ...        1.000000   

               19            20          21          22          23  \
count  800.000000  8.000000e+02  800.000000  800.000000  800.000000   
mean     0.529861  9.993725e-03    0.134564    0.008863    0.664357   
std      0.306657  7.618583e-02    0.106132    0.072350    0.233386   
min      0.000000  3.821813e-11    0.043003    0.000000    0.166873   
25%      0.352941  4.857226e-11    0.062040    0.000000    0.470909   
50%      0.554643  5.346829e-11    0.101057    0.000000    0.672806   
75%      0.747455  5.854692e-11    0.172523    0.000000    0.850000   
max      1.000000  1.000000e+00    1.000000    1.000000    1.000000   

               24          25          26          27  
count  800.000000  800.000000  800.000000  800.000000  
mean     0.181100    0.044782    0.062290    0.041602  
std      0.102657    0.121545    0.073273    0.071724  
min      0.090491    0.000000    0.008621    0.002252  
25%      0.110600    0.000000    0.025862    0.011261  
50%      0.148401    0.000000    0.047414    0.024775  
75%      0.222304    0.000000    0.081897    0.049550  
max      1.000000    1.000000    1.000000    1.000000  

[8 rows x 28 columns]

In [23]:
x_train_norma3.describe()

0           1           2           3           4           5   \
count  800.000000  800.000000  800.000000  800.000000  800.000000  800.000000   
mean     0.058224    0.079056    0.065179    0.209439    0.008604    0.078408   
std      0.090903    0.086854    0.166279    0.254011    0.052847    0.090103   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.026316    0.022222    0.000000    0.066667    0.000342    0.019082   
50%      0.026316    0.044444    0.000000    0.133333    0.001537    0.052601   
75%      0.078947    0.111111    0.000000    0.227273    0.005573    0.116997   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               6           7           8           9      ...              18  \
count  800.000000  800.000000  800.000000  800.000000     ...      800.000000   
mean     0.268503    0.214836    0.311069    0.011250     ...        0.169030   
std      0.211424    0.192675    0.170536    0.078301     ...        0.172761   
min      0.000000    0.000000    0.000000    0.000000     ...        0.000000   
25%      0.111658    0.092550    0.266667    0.000000     ...        0.000000   
50%      0.244186    0.138380    0.299626    0.000000     ...        0.157999   
75%      0.400542    0.279801    0.405096    0.000000     ...        0.277369   
max      1.000000    1.000000    1.000000    1.000000     ...        1.000000   

               19            20          21          22          23  \
count  800.000000  8.000000e+02  800.000000  800.000000  800.000000   
mean     0.529861  9.993724e-03    0.095676    0.008863    0.597128   
std      0.306657  7.618583e-02    0.110901    0.072350    0.280132   
min      0.000000  0.000000e+00    0.000000    0.000000    0.000000   
25%      0.352941  1.035413e-11    0.019893    0.000000    0.364934   
50%      0.554643  1.525016e-11    0.060662    0.000000    0.607270   
75%      0.747455  2.032879e-11    0.135340    0.000000    0.819956   
max      1.000000  1.000000e+00    1.000000    1.000000    1.000000   

               24          25          26          27  
count  800.000000  800.000000  800.000000  800.000000  
mean     0.099624    0.044782    0.054136    0.039438  
std      0.112870    0.121545    0.073910    0.071886  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.022110    0.000000    0.017391    0.009029  
50%      0.063672    0.000000    0.039130    0.022573  
75%      0.144928    0.000000    0.073913    0.047404  
max      1.000000    1.000000    1.000000    1.000000  

[8 rows x 28 columns]

In [24]:
x_train_norma4.describe()

0           1          2           3           4           5   \
count  800.000000  800.000000  800.00000  800.000000  800.000000  800.000000   
mean     0.606250    0.389375    0.45625    0.473865    1.351020    0.263567   
std      1.727155    0.977106    1.16395    1.581576   10.102660    0.920222   
min     -0.500000   -0.500000    0.00000   -0.830189   -0.293878   -0.537214   
25%      0.000000   -0.250000    0.00000   -0.415094   -0.228571   -0.342330   
50%      0.000000    0.000000    0.00000    0.000000    0.000000    0.000000   
75%      1.000000    0.750000    0.00000    0.584906    0.771429    0.657670   
max     18.500000   10.750000    7.00000    5.396226  190.873469    9.675746   

               6           7             8           9      ...      \
count  800.000000  800.000000  8.000000e+02  800.000000     ...       
mean     0.084174    0.408303  8.266807e-02    0.022500     ...       
std      0.731864    1.028964  1.231940e+00    0.156603     ...       
min     -0.845272   -0.739008 -2.164471e+00    0.000000     ...       
25%     -0.458759   -0.244755 -2.380935e-01    0.000000     ...       
50%      0.000000    0.000000 -1.691355e-16    0.000000     ...       
75%      0.541241    0.755245  7.619065e-01    0.000000     ...       
max      2.616318    4.601399  5.059445e+00    2.000000     ...       

               18            19            20          21          22  \
count  800.000000  8.000000e+02  8.000000e+02  800.000000  800.000000   
mean     0.039768 -6.281627e-02  1.001911e+09    0.303286    0.002216   
std      0.622858  7.773041e-01  7.637938e+09    0.960623    0.018087   
min     -0.569637 -1.405890e+00 -1.528890e+00   -0.525456    0.000000   
25%     -0.569637 -5.112668e-01 -4.908467e-01   -0.353142    0.000000   
50%      0.000000  1.055471e-16  0.000000e+00    0.000000    0.000000   
75%      0.430363  4.887332e-01  5.091533e-01    0.646858    0.000000   
max      3.035675  1.128877e+00  1.002540e+11    8.136517    0.250000   

               23          24          25          26          27  
count  800.000000  800.000000  800.000000  800.000000  800.000000  
mean    -0.022289    0.292727    0.026869    0.265481    0.439485  
std      0.615646    0.919000    0.072927    1.307639    1.873259  
min     -1.334597   -0.518422    0.000000   -0.692308   -0.588235  
25%     -0.532582   -0.338403    0.000000   -0.384615   -0.352941  
50%      0.000000    0.000000    0.000000    0.000000    0.000000  
75%      0.467418    0.661597    0.000000    0.615385    0.647059  
max      0.863101    7.623665    0.600000   17.000000   25.470588  

[8 rows x 28 columns]

## verificando os dados normalizados de teste

In [25]:
x_test_norma0.describe()

0             1             2             3             4   \
count  2.000000e+02  2.000000e+02  2.000000e+02  2.000000e+02  2.000000e+02   
mean   1.415534e-16 -4.884981e-17  1.620926e-16  1.110223e-17  5.773160e-17   
std    1.002509e+00  1.002509e+00  1.002509e+00  1.002509e+00  1.002509e+00   
min   -8.641639e-01 -9.408693e-01 -3.593313e-01 -9.159964e-01 -4.504709e-01   
25%   -4.426205e-01 -6.708924e-01 -3.593313e-01 -5.828276e-01 -4.150287e-01   
50%   -4.426205e-01 -4.009156e-01 -3.593313e-01 -2.413063e-01 -3.512327e-01   
75%    4.004662e-01  4.090149e-01 -3.593313e-01  1.155180e-01 -2.161977e-02   
max    6.302073e+00  4.188691e+00  5.775593e+00  3.490473e+00  6.637978e+00   

                 5             6             7             8             9   \
count  2.000000e+02  2.000000e+02  2.000000e+02  2.000000e+02  2.000000e+02   
mean   7.438494e-17 -7.294165e-16 -1.154632e-16 -2.296774e-16 -3.386180e-17   
std    1.002509e+00  1.002509e+00  1.002509e+00  1.002509e+00  1.002509e+00   
min   -9.027711e-01 -1.324724e+00 -1.097854e+00 -1.942019e+00 -9.529814e-02   
25%   -6.568227e-01 -7.234037e-01 -6.720706e-01 -2.620970e-01 -9.529814e-02   
50%   -3.655345e-01 -1.220835e-01 -2.917073e-01 -1.385028e-01 -9.529814e-02   
75%    2.392926e-01  5.295019e-01  3.860265e-01  5.446350e-01 -9.529814e-02   
max    4.234249e+00  3.142226e+00  4.452429e+00  3.226664e+00  1.261112e+01   

           ...                 18            19            20            21  \
count      ...       2.000000e+02  2.000000e+02  2.000000e+02  2.000000e+02   
mean       ...       8.770762e-17  1.576517e-16  1.852685e-17  1.426637e-16   
std        ...       1.002509e+00  1.002509e+00  1.002509e+00  1.002509e+00   
min        ...      -9.097458e-01 -1.894542e+00 -9.383220e-02 -8.451465e-01   
25%        ...      -9.097458e-01 -5.748411e-01 -9.383220e-02 -6.449803e-01   
50%        ...      -1.973713e-01  8.707381e-02 -9.383220e-02 -3.876236e-01   
75%        ...       6.467339e-01  6.484774e-01 -9.383220e-02  1.957181e-01   
max        ...       4.347133e+00  1.573286e+00  1.287207e+01  4.320683e+00   

                 22            23            24            25            26  \
count  2.000000e+02  2.000000e+02  2.000000e+02  2.000000e+02  2.000000e+02   
mean   1.444678e-16 -4.024558e-17 -6.883383e-17 -1.060263e-16 -2.775558e-17   
std    1.002509e+00  1.002509e+00  1.002509e+00  1.002509e+00  1.002509e+00   
min   -1.099576e-01 -2.185528e+00 -8.740082e-01 -3.658273e-01 -1.098886e+00   
25%   -1.099576e-01 -7.182988e-01 -6.537143e-01 -3.658273e-01 -7.105872e-01   
50%   -1.099576e-01  1.514480e-01 -4.018239e-01 -3.658273e-01 -3.222882e-01   
75%   -1.099576e-01  7.284726e-01  2.637523e-01 -3.658273e-01  4.785785e-01   
max    1.231134e+01  1.471876e+00  4.193523e+00  6.644502e+00  4.628524e+00   

                 27  
count  2.000000e+02  
mean   4.996004e-18  
std    1.002509e+00  
min   -8.308634e-01  
25%   -6.516692e-01  
50%   -3.530124e-01  
75%    3.040327e-01  
max    4.963080e+00  

[8 rows x 28 columns]

In [26]:
x_test_norma1.describe()

0             1             2           3             4   \
count  2.000000e+02  2.000000e+02  2.000000e+02  200.000000  2.000000e+02   
mean   9.974714e-02  9.106147e-02  4.730603e-02    0.011091  8.210720e-01   
std    9.044608e-02  5.753607e-02  4.345273e-02    0.025288  1.689782e-01   
min    4.119968e-10  3.686287e-10  9.215718e-11    0.000000  6.266689e-09   
25%    2.090100e-02  4.320456e-02  1.070934e-02    0.000364  7.206729e-01   
50%    7.158201e-02  8.222313e-02  3.411120e-02    0.002113  8.788364e-01   
75%    1.654782e-01  1.292491e-01  7.381971e-02    0.008070  9.599913e-01   
max    3.115010e-01  2.342929e-01  1.998187e-01    0.117146  9.950757e-01   

                 5             6             7           8             9   \
count  2.000000e+02  2.000000e+02  2.000000e+02  200.000000  2.000000e+02   
mean   5.727080e-02  5.362927e-02  1.449740e-02    0.010323  1.951564e-12   
std    4.420604e-02  4.653923e-02  2.574421e-02    0.010991  1.949686e-11   
min    1.870249e-10  1.409463e-10  8.809143e-12    0.000000  0.000000e+00   
25%    1.998752e-02  1.387743e-02  8.258587e-04    0.001383  0.000000e+00   
50%    4.613573e-02  4.099725e-02  4.753005e-03    0.006795  0.000000e+00   
75%    8.610477e-02  8.279976e-02  1.686582e-02    0.015813  0.000000e+00   
max    1.998187e-01  1.998187e-01  1.998187e-01    0.041418  2.059984e-10   

           ...               18          19          20            21  \
count      ...       200.000000  200.000000  200.000000  2.000000e+02   
mean       ...         0.003341    0.006602    0.047649  6.973104e-02   
std        ...         0.008864    0.009185    0.104066  5.009092e-02   
min        ...         0.000000    0.000000    0.000350  2.276825e-10   
25%        ...         0.000000    0.000690    0.006215  2.680132e-02   
50%        ...         0.000800    0.002639    0.023959  5.728908e-02   
75%        ...         0.002979    0.009147    0.056363  9.948402e-02   
max        ...         0.068154    0.039049    1.000000  1.998187e-01   

               22            23            24          25            26  \
count  200.000000  2.000000e+02  2.000000e+02  200.000000  2.000000e+02   
mean     0.000008  3.524300e-02  5.531262e-02    0.000348  2.803011e-01   
std      0.000109  4.051414e-02  4.457075e-02    0.001538  1.696959e-01   
min      0.000000  4.668675e-11  1.535953e-10    0.000000  1.566672e-09   
25%      0.000000  4.543555e-03  1.822909e-02    0.000000  1.333115e-01   
50%      0.000000  2.025041e-02  4.241179e-02    0.000000  2.752041e-01   
75%      0.000000  5.131601e-02  8.432909e-02    0.000000  4.136955e-01   
max      0.001547  1.998187e-01  1.998187e-01    0.014455  6.230020e-01   

                 27  
count  2.000000e+02  
mean   2.491411e-01  
std    1.174880e-01  
min    1.843144e-09  
25%    1.501533e-01  
50%    2.583143e-01  
75%    3.160358e-01  
max    5.510792e-01  

[8 rows x 28 columns]

In [27]:
x_test_norma2.describe()

0           1           2           3           4           5   \
count  200.000000  200.000000  200.000000  200.000000  200.000000  200.000000   
mean     0.169444    0.224250    0.176250    0.207875    0.064486    0.284323   
std      0.132122    0.185666    0.142984    0.227509    0.141287    0.169445   
min      0.055556    0.050000    0.125000    0.000000    0.000999    0.131736   
25%      0.111111    0.100000    0.125000    0.075609    0.005994    0.173306   
50%      0.111111    0.150000    0.125000    0.153114    0.014985    0.222540   
75%      0.222222    0.300000    0.125000    0.234091    0.061439    0.324768   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               6           7           8           9      ...              18  \
count  200.000000  200.000000  200.000000  200.000000     ...      200.000000   
mean     0.542765    0.217907    0.375728    0.007500     ...        0.173058   
std      0.145878    0.176096    0.193958    0.078898     ...        0.190704   
min      0.350000    0.025063    0.000000    0.000000     ...        0.000000   
25%      0.437500    0.099854    0.325019    0.000000     ...        0.000000   
50%      0.525000    0.166667    0.348932    0.000000     ...        0.135513   
75%      0.619814    0.285714    0.481100    0.000000     ...        0.296084   
max      1.000000    1.000000    1.000000    1.000000     ...        1.000000   

               19            20          21          22          23  \
count  200.000000  2.000000e+02  200.000000  200.000000  200.000000   
mean     0.546320  7.236842e-03    0.223759    0.008852    0.670014   
std      0.289089  7.731890e-02    0.180108    0.080709    0.224757   
min      0.000000  5.397778e-11    0.071923    0.000000    0.180032   
25%      0.380556  6.911789e-11    0.107884    0.000000    0.508976   
50%      0.571429  7.590168e-11    0.154120    0.000000    0.703968   
75%      0.733318  8.246887e-11    0.258921    0.000000    0.833333   
max      1.000000  1.000000e+00    1.000000    1.000000    1.000000   

               24          25          26          27  
count  200.000000  200.000000  200.000000  200.000000  
mean     0.295053    0.052184    0.218361    0.160707  
std      0.168526    0.143005    0.169298    0.169532  
min      0.148129    0.000000    0.032787    0.020202  
25%      0.185161    0.000000    0.098361    0.050505  
50%      0.227505    0.000000    0.163934    0.101010  
75%      0.339391    0.000000    0.299180    0.212121  
max      1.000000    1.000000    1.000000    1.000000  

[8 rows x 28 columns]

In [28]:
x_test_norma3.describe()

0           1           2           3           4           5   \
count  200.000000  200.000000  200.000000  200.000000  200.000000  200.000000   
mean     0.120588    0.183421    0.058571    0.207875    0.063550    0.175738   
std      0.139893    0.195438    0.163410    0.227509    0.141429    0.195154   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.058824    0.052632    0.000000    0.075609    0.005000    0.047878   
50%      0.058824    0.105263    0.000000    0.153114    0.014000    0.104581   
75%      0.176471    0.263158    0.000000    0.234091    0.060500    0.222320   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               6           7           8           9      ...              18  \
count  200.000000  200.000000  200.000000  200.000000     ...      200.000000   
mean     0.296561    0.197801    0.375728    0.007500     ...        0.173058   
std      0.224428    0.180623    0.193958    0.078898     ...        0.190704   
min      0.000000    0.000000    0.000000    0.000000     ...        0.000000   
25%      0.134615    0.076714    0.325019    0.000000     ...        0.000000   
50%      0.269231    0.145244    0.348932    0.000000     ...        0.135513   
75%      0.415099    0.267352    0.481100    0.000000     ...        0.296084   
max      1.000000    1.000000    1.000000    1.000000     ...        1.000000   

               19            20          21          22          23  \
count  200.000000  2.000000e+02  200.000000  200.000000  200.000000   
mean     0.546320  7.236842e-03    0.163603    0.008852    0.597563   
std      0.289089  7.731890e-02    0.194066    0.080709    0.274104   
min      0.000000  0.000000e+00    0.000000    0.000000    0.000000   
25%      0.380556  1.514011e-11    0.038748    0.000000    0.401167   
50%      0.571429  2.192390e-11    0.088567    0.000000    0.638971   
75%      0.733318  2.849109e-11    0.201490    0.000000    0.796740   
max      1.000000  1.000000e+00    1.000000    1.000000    1.000000   

               24          25          26          27  
count  200.000000  200.000000  200.000000  200.000000  
mean     0.172472    0.052184    0.191864    0.143402  
std      0.197830    0.143005    0.175037    0.173027  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.043472    0.000000    0.067797    0.030928  
50%      0.093178    0.000000    0.135593    0.082474  
75%      0.224520    0.000000    0.275424    0.195876  
max      1.000000    1.000000    1.000000    1.000000  

[8 rows x 28 columns]

In [29]:
x_test_norma4.describe()

0           1           2             3           4   \
count  200.000000  200.000000  200.000000  2.000000e+02  200.000000   
mean     0.525000    0.371250    0.410000  3.455399e-01    0.892793   
std      1.189094    0.928329    1.143872  1.435549e+00    2.548263   
min     -0.500000   -0.500000    0.000000 -9.661266e-01   -0.252252   
25%      0.000000   -0.250000    0.000000 -4.890434e-01   -0.162162   
50%      0.000000    0.000000    0.000000 -8.760354e-17    0.000000   
75%      1.000000    0.750000    0.000000  5.109566e-01    0.837838   
max      8.000000    4.250000    7.000000  5.343743e+00   17.765766   

               5           6           7           8           9      ...      \
count  200.000000  200.000000  200.000000  200.000000  200.000000     ...       
mean     0.407910    0.097440    0.275691    0.171684    0.015000     ...       
std      1.118728    0.800148    0.947464    1.242680    0.157796     ...       
min     -0.599517   -0.959881   -0.761883   -2.235583    0.000000     ...       
25%     -0.325057   -0.479941   -0.359479   -0.153204    0.000000     ...       
50%      0.000000    0.000000    0.000000    0.000000    0.000000     ...       
75%      0.674943    0.520059    0.640521    0.846796    0.000000     ...       
max      5.133027    2.605392    4.483650    4.171356    2.000000     ...       

                 18          19            20          21          22  \
count  2.000000e+02  200.000000  2.000000e+02  200.000000  200.000000   
mean   1.268062e-01   -0.071178  5.420459e+08    0.461073    0.001562   
std    6.440877e-01    0.819500  5.791254e+09    1.192472    0.014243   
min   -4.576832e-01   -1.619869 -1.642120e+00   -0.544218    0.000000   
25%   -4.576832e-01   -0.541081 -5.081121e-01   -0.306122    0.000000   
50%   -4.683753e-17    0.000000  3.833739e-16    0.000000    0.000000   
75%    5.423168e-01    0.458919  4.918879e-01    0.693878    0.000000   
max    2.919733e+00    1.214902  7.490089e+10    5.600471    0.176471   

                 23            24          25          26          27  
count  2.000000e+02  2.000000e+02  200.000000  200.000000  200.000000  
mean  -1.046800e-01  4.379712e-01    0.030441    0.271020    0.369375  
std    6.929287e-01  1.092693e+00    0.083419    0.843036    1.048977  
min   -1.615304e+00 -5.146610e-01    0.000000   -0.653061   -0.500000  
25%   -6.011639e-01 -2.745499e-01    0.000000   -0.326531   -0.312500  
50%    1.713039e-16  1.066313e-16    0.000000    0.000000    0.000000  
75%    3.988361e-01  7.254501e-01    0.000000    0.673469    0.687500  
max    9.126723e-01  5.008734e+00    0.583333    4.163265    5.562500  

[8 rows x 28 columns]

## Criando os modelos e utilizando os dados de treino normalizados


### utilizando o algoritmo RandomForestClassifier


In [30]:
# x_train_norma0 = standardscales

rf = RandomForestClassifier()
rf.fit(x_train_norma0, y_train)

pred = rf.predict(x_train_norma0)
print ('standardscales')
print('accuracy', accuracy_score(y_train,pred))
print('precision', precision_score(y_train,pred,average='micro' ))
print('recall', recall_score(y_train,pred,average='micro'))
print('f1', f1_score(y_train,pred,average='micro'))
confusion_matrix(y_train,pred)

C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


standardscales
('accuracy', 0.65875)
('precision', 0.65875)
('recall', 0.65875)
('f1', 0.65875)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
# x_train_norma1 = normalize

rf1 = RandomForestClassifier()
rf1.fit(x_train_norma1, y_train)

pred1 = rf1.predict(x_train_norma1)
print ('normalize')
print('accuracy', accuracy_score(y_train,pred1))
print('precision', precision_score(y_train,pred1 ,average='micro'))
print('recall', recall_score(y_train,pred1,average='micro'))
print('f1', f1_score(y_train,pred1,average='micro'))
confusion_matrix(y_train,pred1)

C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


normalize
('accuracy', 0.64375)
('precision', 0.64375)
('recall', 0.64375)
('f1', 0.64375)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
# x_train_norma2 = maxabsscaler

rf2 = RandomForestClassifier()
rf2.fit(x_train_norma2, y_train)

pred2 = rf2.predict(x_train_norma2)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_train,pred2))
print('precision', precision_score(y_train,pred2 ,average='micro'))
print('recall', recall_score(y_train,pred2,average='micro'))
print('f1', f1_score(y_train,pred2,average='micro'))
confusion_matrix(y_train,pred2)

C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


maxabsscaler
('accuracy', 0.66)
('precision', 0.66)
('recall', 0.66)
('f1', 0.66)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [33]:
# x_train_norma3 = minmaxscaler

rf3 = RandomForestClassifier()
rf3.fit(x_train_norma3, y_train)

pred3 = rf3.predict(x_train_norma3)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_train,pred3))
print('precision', precision_score(y_train,pred3,average='micro' ))
print('recall', recall_score(y_train,pred3,average='micro'))
print('f1', f1_score(y_train,pred3,average='micro'))
confusion_matrix(y_train,pred3)

C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


minmaxscaler
('accuracy', 0.6625)
('precision', 0.6625)
('recall', 0.6625)
('f1', 0.6625)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
# x_train_norma4 = robustscaler

rf4 = RandomForestClassifier()
rf4.fit(x_train_norma4, y_train)

pred4 = rf4.predict(x_train_norma4)
print ('robustscaler')
print('accuracy', accuracy_score(y_train,pred4))
print('precision', precision_score(y_train,pred4,average='micro' ))
print('recall', recall_score(y_train,pred4,average='micro'))
print('f1', f1_score(y_train,pred4,average='micro'))
confusion_matrix(y_train,pred4)

C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


robustscaler
('accuracy', 0.66125)
('precision', 0.66125)
('recall', 0.66125)
('f1', 0.66125)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### Utilizando o algoritmo GaussianNB

In [35]:
# x_train_norma0 = standardscales

gnb = GaussianNB()
gnb.fit(x_train_norma0, y_train)

pred = gnb.predict(x_train_norma0)
print ('standardscales')
print('accuracy', accuracy_score(y_train,pred))
print('precision', precision_score(y_train,pred,average='micro' ))
print('recall', recall_score(y_train,pred,average='micro'))
print('f1', f1_score(y_train,pred,average='micro'))
confusion_matrix(y_train,pred)

standardscales
('accuracy', 0.665)
('precision', 0.665)
('recall', 0.665)
('f1', 0.665)


C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
# x_train_norma1 = normalize

gnb1 = GaussianNB()
gnb1.fit(x_train_norma1, y_train)

pred1 = gnb1.predict(x_train_norma1)
print ('normalize')
print('accuracy', accuracy_score(y_train,pred1))
print('precision', precision_score(y_train,pred1,average='micro' ))
print('recall', recall_score(y_train,pred1,average='micro'))
print('f1', f1_score(y_train,pred1,average='micro'))
confusion_matrix(y_train,pred1)

C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


normalize
('accuracy', 0.665)
('precision', 0.665)
('recall', 0.665)
('f1', 0.665)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
# x_train_norma2 = maxabsscaler

gnb2 = GaussianNB()
gnb2.fit(x_train_norma2, y_train)

pred2 = gnb2.predict(x_train_norma2)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_train,pred2))
print('precision', precision_score(y_train,pred2,average='micro' ))
print('recall', recall_score(y_train,pred2,average='micro'))
print('f1', f1_score(y_train,pred2,average='micro'))
confusion_matrix(y_train,pred2)

C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


maxabsscaler
('accuracy', 0.665)
('precision', 0.665)
('recall', 0.665)
('f1', 0.665)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
# x_train_norma3 = minmaxscaler

gnb3 = GaussianNB()
gnb3.fit(x_train_norma3, y_train)

pred3 = gnb3.predict(x_train_norma3)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_train,pred3))
print('precision', precision_score(y_train,pred3,average='micro' ))
print('recall', recall_score(y_train,pred3,average='micro'))
print('f1', f1_score(y_train,pred3,average='micro'))
confusion_matrix(y_train,pred3)

C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


minmaxscaler
('accuracy', 0.665)
('precision', 0.665)
('recall', 0.665)
('f1', 0.665)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [39]:
# x_train_norma4 = robustscaler

gnb4 = GaussianNB()
gnb4.fit(x_train_norma4, y_train)

pred4 = gnb4.predict(x_train_norma4)
print ('robustscaler')
print('accuracy', accuracy_score(y_train,pred4))
print('precision', precision_score(y_train,pred4,average='micro' ))
print('recall', recall_score(y_train,pred4,average='micro'))
print('f1', f1_score(y_train,pred4,average='micro'))
confusion_matrix(y_train,pred4)

C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


robustscaler
('accuracy', 0.05375)
('precision', 0.05375)
('recall', 0.05375)
('f1', 0.05374999999999999)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Testando utilizando os dados de treino normalizados

### Com o algoritmo RandomForestClassifier

In [40]:
# x_test_norma0 = standardscales

pred = rf.predict(x_test_norma0)
print ('standardscales')
print('accuracy', accuracy_score(y_test,pred))
print('precision', precision_score(y_test,pred,average='micro' ))
print('recall', recall_score(y_test,pred,average='micro'))
print('f1', f1_score(y_test,pred,average='micro'))
confusion_matrix(y_test,pred)

standardscales
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [41]:
# x_test_norma1 = normalize

pred1 = rf1.predict(x_test_norma1)
print ('normalize')
print('accuracy', accuracy_score(y_test,pred1))
print('precision', precision_score(y_test,pred1,average='micro' ))
print('recall', recall_score(y_test,pred1,average='micro'))
print('f1', f1_score(y_test,pred1,average='micro'))
confusion_matrix(y_test,pred1)

normalize
('accuracy', 0.005)
('precision', 0.005)
('recall', 0.005)
('f1', 0.005)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [42]:
# x_test_norma2 = maxabsscaler

pred2 = rf2.predict(x_test_norma2)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_test,pred2))
print('precision', precision_score(y_test,pred2,average='micro' ))
print('recall', recall_score(y_test,pred2,average='micro'))
print('f1', f1_score(y_test,pred2,average='micro'))
confusion_matrix(y_test,pred2)

maxabsscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [43]:
# x_test_norma3 = minmaxscaler

pred3 = rf3.predict(x_test_norma3)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_test,pred3))
print('precision', precision_score(y_test,pred3,average='micro' ))
print('recall', recall_score(y_test,pred3,average='micro'))
print('f1', f1_score(y_test,pred3,average='micro'))
confusion_matrix(y_test,pred3)

minmaxscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [44]:
# x_test_norma4 = robustscaler

pred4 = rf4.predict(x_test_norma4)
print ('robustscaler')
print('accuracy', accuracy_score(y_test,pred4))
print('precision', precision_score(y_test,pred4,average='micro' ))
print('recall', recall_score(y_test,pred4,average='micro'))
print('f1', f1_score(y_test,pred4,average='micro'))
confusion_matrix(y_test,pred4)

robustscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### Utilizando o algoritmo GaussianNB

In [45]:
# x_test_norma0 = standardscales

pred = gnb.predict(x_test_norma0)
print ('standardscales')
print('accuracy', accuracy_score(y_test,pred))
print('precision', precision_score(y_test,pred,average='micro' ))
print('recall', recall_score(y_test,pred,average='micro'))
print('f1', f1_score(y_test,pred,average='micro'))
confusion_matrix(y_test,pred)

standardscales
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [46]:
# x_test_norma1 = normalize

pred1 = gnb1.predict(x_test_norma0)
print ('normalize')
print('accuracy', accuracy_score(y_test,pred1))
print('precision', precision_score(y_test,pred1,average='micro' ))
print('recall', recall_score(y_test,pred1,average='micro'))
print('f1', f1_score(y_test,pred1,average='micro'))
confusion_matrix(y_test,pred1)

normalize
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
# x_test_norma2 = maxabsscaler

pred2 = gnb2.predict(x_test_norma2)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_test,pred2))
print('precision', precision_score(y_test,pred2,average='micro' ))
print('recall', recall_score(y_test,pred2,average='micro'))
print('f1', f1_score(y_test,pred2,average='micro'))
confusion_matrix(y_test,pred2)

maxabsscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [48]:
# x_test_norma3 = minmaxscaler

pred3 = gnb3.predict(x_test_norma3)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_test,pred3))
print('precision', precision_score(y_test,pred3,average='micro' ))
print('recall', recall_score(y_test,pred3,average='micro'))
print('f1', f1_score(y_test,pred3,average='micro'))
confusion_matrix(y_test,pred3)

minmaxscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
# x_test_norma4 = robustscaler

pred4 = gnb4.predict(x_test_norma4)
print ('robustscaler')
print('accuracy', accuracy_score(y_test,pred4))
print('precision', precision_score(y_test,pred4,average='micro' ))
print('recall', recall_score(y_test,pred4,average='micro'))
print('f1', f1_score(y_test,pred4,average='micro'))
confusion_matrix(y_test,pred4)

robustscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Criando os modelos e utilizando os dados de treino normalizados e com pca

### Instanciando o pca

In [50]:
pca = PCA()
pca.fit(x_train_norma0)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [51]:
# Verificando o pca
pca.explained_variance_.round(3)

array([1.0405e+01, 4.7390e+00, 4.2010e+00, 1.8390e+00, 1.7890e+00,
       1.3950e+00, 8.4000e-01, 5.9400e-01, 5.3800e-01, 4.6800e-01,
       2.9600e-01, 2.4400e-01, 1.6300e-01, 1.3900e-01, 1.0400e-01,
       9.3000e-02, 5.1000e-02, 4.7000e-02, 3.2000e-02, 2.5000e-02,
       1.4000e-02, 8.0000e-03, 6.0000e-03, 4.0000e-03, 3.0000e-03,
       1.0000e-03, 0.0000e+00, 0.0000e+00])

### Normalizando e aplicando o pca no x de teste e de treino

In [52]:
x_teste_pca = pca.transform(x_test)
x_train_pca = pca.transform(x_train)

x_test_norma0_pca = pd.DataFrame(standardscales.fit_transform(x_teste_pca))
x_test_norma1_pca = pd.DataFrame(normalize.fit_transform(x_teste_pca))
x_test_norma2_pca = pd.DataFrame(maxabsscaler.fit_transform(x_teste_pca))
x_test_norma3_pca = pd.DataFrame(minmaxscaler.fit_transform(x_teste_pca))
x_test_norma4_pca = pd.DataFrame(robustscaler.fit_transform(x_teste_pca))

x_train_norma0_pca = pd.DataFrame(standardscales.fit_transform(x_train_pca))
x_train_norma1_pca = pd.DataFrame(normalize.fit_transform(x_train_pca))
x_train_norma2_pca = pd.DataFrame(maxabsscaler.fit_transform(x_train_pca))
x_train_norma3_pca = pd.DataFrame(minmaxscaler.fit_transform(x_train_pca))
x_train_norma4_pca = pd.DataFrame(robustscaler.fit_transform(x_train_pca))

### Com o algoritmo RandomForestClassifier

In [53]:
# x_train_norma0 = standardscales

rf_pca = RandomForestClassifier()
rf_pca.fit(x_train_norma0_pca, y_train)

pred_pca = rf_pca.predict(x_train_norma0_pca)
print ('standardscales')
print('accuracy', accuracy_score(y_train,pred_pca))
print('precision', precision_score(y_train,pred_pca ,average='micro'))
print('recall', recall_score(y_train,pred_pca,average='micro'))
print('f1', f1_score(y_train,pred_pca,average='micro'))
confusion_matrix(y_train,pred_pca)


standardscales
('accuracy', 0.555)
('precision', 0.555)
('recall', 0.555)
('f1', 0.555)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [54]:
# x_teste_norma0 = standardscales

pred_pca = rf_pca.predict(x_test_norma0_pca)
print ('standardscales')
print('accuracy', accuracy_score(y_test,pred_pca))
print('precision', precision_score(y_test,pred_pca ,average='micro'))
print('recall', recall_score(y_test,pred_pca,average='micro'))
print('f1', f1_score(y_test,pred_pca,average='micro'))
confusion_matrix(y_test,pred_pca)

standardscales
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [55]:
# x_train_norma1 = normalize

rf_pca1 = RandomForestClassifier()
rf_pca1.fit(x_train_norma1_pca, y_train)

pred1_pca = rf_pca1.predict(x_train_norma1_pca)
print ('normalize')
print('accuracy', accuracy_score(y_train,pred1_pca))
print('precision', precision_score(y_train,pred1_pca ,average='micro'))
print('recall', recall_score(y_train,pred1_pca,average='micro'))
print('f1', f1_score(y_train,pred1_pca,average='micro'))
confusion_matrix(y_train,pred1_pca)

C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


normalize
('accuracy', 0.64125)
('precision', 0.64125)
('recall', 0.64125)
('f1', 0.64125)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [56]:
# x_teste_norma1 = normalize

pred1_pca = rf_pca1.predict(x_test_norma1_pca)
print ('normalize')
print('accuracy', accuracy_score(y_test,pred1_pca))
print('precision', precision_score(y_test,pred1_pca ,average='micro'))
print('recall', recall_score(y_test,pred1_pca,average='micro'))
print('f1', f1_score(y_test,pred1_pca,average='micro'))
confusion_matrix(y_test,pred1_pca)

normalize
('accuracy', 0.005)
('precision', 0.005)
('recall', 0.005)
('f1', 0.005)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [57]:
# x_train_norma2 = maxabsscaler

rf_pca2 = RandomForestClassifier()
rf_pca2.fit(x_train_norma2_pca, y_train)

pred2_pca = rf_pca2.predict(x_train_norma2_pca)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_train,pred2_pca))
print('precision', precision_score(y_train,pred2_pca ,average='micro'))
print('recall', recall_score(y_train,pred2_pca,average='micro'))
print('f1', f1_score(y_train,pred2_pca,average='micro'))
confusion_matrix(y_train,pred2_pca)


maxabsscaler
('accuracy', 0.17625)
('precision', 0.17625)
('recall', 0.17625)
('f1', 0.17625)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [58]:
# x_teste_norma2 = maxabsscaler

pred2_pca = rf_pca2.predict(x_test_norma2_pca)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_test,pred2_pca))
print('precision', precision_score(y_test,pred2_pca ,average='micro'))
print('recall', recall_score(y_test,pred2_pca,average='micro'))
print('f1', f1_score(y_test,pred2_pca,average='micro'))
confusion_matrix(y_test,pred2_pca)

maxabsscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [59]:
# x_train_norma3 = minmaxscaler

rf_pca3 = RandomForestClassifier()
rf_pca3.fit(x_train_norma3_pca, y_train)

pred3_pca = rf_pca3.predict(x_train_norma3_pca)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_train,pred3_pca))
print('precision', precision_score(y_train,pred3_pca ,average='micro'))
print('recall', recall_score(y_train,pred3_pca,average='micro'))
print('f1', f1_score(y_train,pred3_pca,average='micro'))
confusion_matrix(y_train,pred3_pca)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


minmaxscaler
('accuracy', 0.1575)
('precision', 0.1575)
('recall', 0.1575)
('f1', 0.1575)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [60]:
# x_teste_norma3 = minmaxscaler

pred3_pca = rf_pca3.predict(x_test_norma3_pca)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_test,pred3_pca))
print('precision', precision_score(y_test,pred3_pca ,average='micro'))
print('recall', recall_score(y_test,pred3_pca,average='micro'))
print('f1', f1_score(y_test,pred3_pca,average='micro'))
confusion_matrix(y_test,pred3_pca)

minmaxscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [61]:
# x_train_norma4 = robustscaler

rf_pca4 = RandomForestClassifier()
rf_pca4.fit(x_train_norma4_pca, y_train)

pred4_pca = rf_pca4.predict(x_train_norma4_pca)
print ('robustscaler')
print('accuracy', accuracy_score(y_train,pred4_pca))
print('precision', precision_score(y_train,pred4_pca ,average='micro'))
print('recall', recall_score(y_train,pred4_pca,average='micro'))
print('f1', f1_score(y_train,pred4_pca,average='micro'))
confusion_matrix(y_train,pred4_pca)


C:\Users\alfred\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


robustscaler
('accuracy', 0.65625)
('precision', 0.65625)
('recall', 0.65625)
('f1', 0.65625)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [62]:
# x_teste_norma4 = robustscaler

pred4_pca = rf_pca4.predict(x_test_norma4_pca)
print ('robustscaler')
print('accuracy', accuracy_score(y_test,pred4_pca))
print('precision', precision_score(y_test,pred4_pca ,average='micro'))
print('recall', recall_score(y_test,pred4_pca,average='micro'))
print('f1', f1_score(y_test,pred4_pca,average='micro'))
confusion_matrix(y_test,pred4_pca)

robustscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### Utilizando o algoritmo GaussianNB

In [63]:
# x_train_norma0 = standardscales

gnb_pca = GaussianNB()
gnb_pca.fit(x_train_norma0_pca, y_train)

pred_pca = gnb_pca.predict(x_train_norma0_pca)
print ('standardscales')
print('accuracy', accuracy_score(y_train,pred_pca))
print('precision', precision_score(y_train,pred_pca,average='micro' ))
print('recall', recall_score(y_train,pred_pca,average='micro'))
print('f1', f1_score(y_train,pred_pca,average='micro'))
confusion_matrix(y_train,pred_pca)

standardscales
('accuracy', 0.64)
('precision', 0.64)
('recall', 0.64)
('f1', 0.64)


C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [64]:
# x_teste_norma0 = standardscales

pred_pca = gnb_pca.predict(x_test_norma0_pca)
print ('standardscales')
print('accuracy', accuracy_score(y_test,pred_pca))
print('precision', precision_score(y_test,pred_pca ,average='micro'))
print('recall', recall_score(y_test,pred_pca,average='micro'))
print('f1', f1_score(y_test,pred_pca,average='micro'))
confusion_matrix(y_test,pred_pca)

standardscales
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [65]:
# x_train_norma1 = normalize

gnb_pca1 = GaussianNB()
gnb_pca1.fit(x_train_norma1_pca, y_train)

pred1_pca = gnb_pca1.predict(x_train_norma1_pca)
print ('normalize')
print('accuracy', accuracy_score(y_train,pred1_pca))
print('precision', precision_score(y_train,pred1_pca,average='micro' ))
print('recall', recall_score(y_train,pred1_pca,average='micro'))
print('f1', f1_score(y_train,pred1_pca,average='micro'))
confusion_matrix(y_train,pred1_pca)

normalize
('accuracy', 0.665)
('precision', 0.665)
('recall', 0.665)
('f1', 0.665)


C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [66]:
# x_teste_norma1 = normalize

pred1_pca = gnb_pca1.predict(x_test_norma1_pca)
print ('normalize')
print('accuracy', accuracy_score(y_test,pred1_pca))
print('precision', precision_score(y_test,pred1_pca ,average='micro'))
print('recall', recall_score(y_test,pred1_pca,average='micro'))
print('f1', f1_score(y_test,pred1_pca,average='micro'))
confusion_matrix(y_test,pred1_pca)

normalize
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [69]:
# x_train_norma2 = maxabsscaler

gnb_pca2 = GaussianNB()
gnb_pca2.fit(x_train_norma2_pca, y_train)

pred2_pca = gnb_pca2.predict(x_train_norma2_pca)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_train,pred2_pca))
print('precision', precision_score(y_train,pred2_pca,average='micro' ))
print('recall', recall_score(y_train,pred2_pca,average='micro'))
print('f1', f1_score(y_train,pred2_pca,average='micro'))
confusion_matrix(y_train,pred2_pca)

maxabsscaler
('accuracy', 0.64)
('precision', 0.64)
('recall', 0.64)
('f1', 0.64)


C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [70]:
# x_teste_norma2 = maxabsscaler

pred2_pca = gnb_pca2.predict(x_test_norma2_pca)
print ('maxabsscaler')
print('accuracy', accuracy_score(y_test,pred2_pca))
print('precision', precision_score(y_test,pred2_pca ,average='micro'))
print('recall', recall_score(y_test,pred2_pca,average='micro'))
print('f1', f1_score(y_test,pred2_pca,average='micro'))
confusion_matrix(y_test,pred2_pca)

maxabsscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [71]:
# x_train_norma3 = minmaxscaler

gnb_pca3 = GaussianNB()
gnb_pca3.fit(x_train_norma3_pca, y_train)

pred3_pca = gnb_pca3.predict(x_train_norma3_pca)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_train,pred3_pca))
print('precision', precision_score(y_train,pred3_pca,average='micro' ))
print('recall', recall_score(y_train,pred3_pca,average='micro'))
print('f1', f1_score(y_train,pred3_pca,average='micro'))
confusion_matrix(y_train,pred3_pca)

minmaxscaler
('accuracy', 0.64)
('precision', 0.64)
('recall', 0.64)
('f1', 0.64)


C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [72]:
# x_teste_norma3 = minmaxscaler

pred3_pca = gnb_pca3.predict(x_test_norma3_pca)
print ('minmaxscaler')
print('accuracy', accuracy_score(y_test,pred3_pca))
print('precision', precision_score(y_test,pred3_pca ,average='micro'))
print('recall', recall_score(y_test,pred3_pca,average='micro'))
print('f1', f1_score(y_test,pred3_pca,average='micro'))
confusion_matrix(y_test,pred3_pca)

minmaxscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [73]:
# x_train_norma4 = robustscaler

gnb_pca4 = GaussianNB()
gnb_pca4.fit(x_train_norma4_pca, y_train)

pred4_pca = gnb_pca4.predict(x_train_norma4_pca)
print ('robustscaler')
print('accuracy', accuracy_score(y_train,pred4_pca))
print('precision', precision_score(y_train,pred4_pca,average='micro' ))
print('recall', recall_score(y_train,pred4_pca,average='micro'))
print('f1', f1_score(y_train,pred4_pca,average='micro'))
confusion_matrix(y_train,pred4_pca)

robustscaler
('accuracy', 0.045)
('precision', 0.045)
('recall', 0.045)
('f1', 0.045)


C:\Users\alfred\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [74]:
# x_teste_norma4 = robustscaler

pred4_pca = gnb_pca4.predict(x_test_norma4_pca)
print ('robustscaler')
print('accuracy', accuracy_score(y_test,pred4_pca))
print('precision', precision_score(y_test,pred4_pca ,average='micro'))
print('recall', recall_score(y_test,pred4_pca,average='micro'))
print('f1', f1_score(y_test,pred4_pca,average='micro'))
confusion_matrix(y_test,pred4_pca)

robustscaler
('accuracy', 0.0)
('precision', 0.0)
('recall', 0.0)
('f1', 0.0)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)